### ISSUE TITLE
Service monitor scraping both status port of ingress pod

### ISSUE THREAD

**Issue by GDegrove** [Kong/charts#1005]
Hello,

since the version 2.35.0 of the helm chart, we see that the service monitor tries to scrape 2 ports per pod. 

The release of the version 2.35.0 renamed the port `10254` of the `ingressController` `status`. The service monitor looks for that port name to scrape metrics, making the prometheus scrape job effectively scrape 2 metrics port. 

However, the ingress-controller does not expose any metrics on the port `10254` making half of the job target `unavailable`.

A simple proposition would be to rename the `status` port of the ingress-controller to `status-ingress` so the service monitor does not discover that port and does not try to scrape metrics that are unavailable.

**Comment by GDegrove** [comment]
The PR introducing the bug: https://github.com/Kong/charts/pull/989

**Comment by sgrzemski** [comment]
Yup, after this MR the container has 2 ports named `status` and the ServiceMonitor tries to scrape both. Maybe it should be renamed to something else.

**Comment by PauloFerreira25** [comment]
@czeslavo Could you please revert it?

**Comment by PauloFerreira25** [comment]
The ingressController status port responds 404, if it is up. it responds with an error, what is its function?

**Comment by czeslavo** [comment]
@GDegrove @PauloFerreira25 Thanks for raising this issue. @sgrzemski's https://github.com/Kong/charts/pull/1008 was merged and it has been released in the `kong/kong` [2.37.1](https://github.com/Kong/charts/releases/tag/kong-2.37.1) patch release.
