### ISSUE TITLE
no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"

### ISSUE THREAD

**Issue by aurin-l** [Kong/charts#1016]
Hi, 
I am running EKS 1.26
```
Client Version: v1.26.8-eks-43840fb
Server Version: v1.26.12-eks-5e0fdde 
```
Kong version
```
$ helm ls
NAME                    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                  APP VERSION
kong-admin              kong            3               2021-04-21 16:38:13.328313 +0200 SAST           deployed        kong-2.0.0             2.3
```

I have been trying to upgrade following:
https://github.com/Kong/charts/blob/main/charts/kong/UPGRADE.md#280

In tying to upgrade to 2.14.0 I get the following error:
```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "kong-admin-kong-psp" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```

I have updated the CRDs manually as suggested on the upgrade guide.

This was installed before PodSecurityPolicy Deprecation on EKS 1.25, so the manifest still contains the PodSecurityPolicy and I suspect that is the problem.

**Comment by rainest** [comment]
Do you have `podSecurityPolicy.enabled=true` in your values.yaml? The [current default](https://github.com/Kong/charts/blob/ac23c03cbecdbf13d13e8eb4380bde58e93531d9/charts/kong/values.yaml#L927) has it off, and if it's off the templates [shouldn't generate any PodSecurityPolicy resources at all](https://github.com/Kong/charts/blob/ac23c03cbecdbf13d13e8eb4380bde58e93531d9/charts/kong/templates/psp.yaml#L1).

If it's disabled you shouldn't get any PSPs.

**Comment by aurin-l** [comment]
I have `podSecurityPolicy.enabled=false` 

but have found the problem and solved it by removing the API from the manifest.
https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest

Once removed from here I could run the upgrade.
