### ISSUE TITLE
From OpenSource Kong to Kong Plus in Kubernetes (AKS)

### ISSUE THREAD

**Issue by MostefaKamalLala** [Kong/charts#1030]
Hello,
I was wondering if it is possible to keep using everything within Kubernetes (KIC for example) after upgrading to Kong Plus.
It seems like we have no choice but to use Konnect +.
I would like to keep managing my plugins, consumers, etc in my IaC. I dont need to use Konnect GUI.

**Comment by rainest** [comment]
For detailed information on plans and pricing, you'll want to [contact sales](https://konghq.com/contact-sales/). We use GitHub primarily for bug reports and technical usage questions.

All Konnect plans are able to use [KIC control planes](https://docs.konghq.com/konnect/gateway-manager/kic/). These use Kubernetes resources and KIC to create configuration as you're currently used to. KIC fowards the configuration it generates to Konnect. You can then view, but not modify, that configuration in the Konnect GUI.

When using a paid Konnect plan, KIC pulls a license from Konnect and provides it to the proxy, enabling paid proxy features. On the Plus plan, Konnect will then tally the number of paid resources in that generated configuration and charge you accordingly.

I'm not sure if you're asking about Konnect Plus or the different gateway images. "Plus" is specifically the pay-as-you-go Konnect plan. You can also use the [Kong Gateway Enterprise image](https://docs.konghq.com/gateway/latest/#self-managed) in free mode without a license or Konnect integration. This option is entirely on-premise and provides a locally-hosted GUI.
