### ISSUE TITLE
gateway-operator helm bug: no template "kong.renderTpl"

### ISSUE THREAD

**Issue by jutley** [Kong/charts#1074]
Fairly self-explanatory. The gateway-operator uses a template called `kong.renderTpl` which is not defined.

https://github.com/Kong/charts/blob/main/charts/kong/templates/_helpers.tpl#L35

The `kong` chart does include this template.

https://github.com/Kong/charts/blob/035836a9f54c227157d8d91ea2963401d5a07d31/charts/kong/templates/_helpers.tpl#L1778-L1784

**Comment by pmalek** [comment]
Hi @jutley 👋 

Thanks for spotting that. https://github.com/Kong/charts/pull/1075 should fix it.
