### ISSUE TITLE
Disable Kong response headers

### ISSUE THREAD

**Issue by thiagoanegreiros** [Kong/charts#1080]
I want to disable the Kong response headers

I saw in more one than source that it can be done by adding this env to the proxy container
- name: KONG_HEADERS
  value: "off"

https://stackoverflow.com/questions/61675954/kong-ingress-controller-remove-kong-related-headers
https://stackoverflow.com/questions/58397129/how-to-remove-server-header-with-kong-response-transformer-plugin

Is there any configuration whithin this chart to disable the headers somehow?
Tks

**Comment by thiagoanegreiros** [comment]
I've done it setting the envFrom property.


  set {
    name  = "envFrom[0].configMapRef.name"
    value = kubernetes_config_map.kong_env.metadata[0].name
  }
  
  But would be easier if there was a proxy customEnv property
    set {
    name  = "proxy.customEnv.KONG_HEADERS"
    value = "bundled"
  }

**Comment by programmer04** [comment]
[With Helm](https://docs.konghq.com/kubernetes-ingress-controller/latest/install/helm/#main) you can do it by setting property `gateway.env.headers: OFF` in `values.yaml`
