### ISSUE TITLE
feat: add affinity and tolerations to kong by gateway-operator

### ISSUE THREAD

**Issue by tobiasehlert** [Kong/charts#1110]
It would be great to have the option to set both `affinity` and `tolerations` on the _gateway-operator_ chart somehow.

This would give the opportunity to deploy the _kong/kong-gateway_ container on a certain node and/or to prevent a certain node based on the role of the node.

**Comment by pmalek** [comment]
@tobiasehlert: #1111 should provide this functionality.

**Comment by tobiasehlert** [comment]
hi @pmalek,
thanks for creating a PR on this :)
does the affinity and tolerations apply to the controlplane and dataplane pods as well?

**Comment by pmalek** [comment]
This is for operator Pods only.

To customize `ControlPlane` or `DataPlane` Pods you can use https://docs.konghq.com/gateway-operator/latest/customization/pod-template-spec/
