### ISSUE TITLE
kong/kong-gateway:latest and chart version

### ISSUE THREAD

**Issue by 99hops** [Kong/charts#1130]
Hello friends, 
I am curious why the latest 2.41.1 chart from 5 Sept ships with 3.6 while the kong/kong-gateway:latest is now at 3.8 :cat: 

Thanks!

**Comment by pmalek** [comment]
#1131 will bump the default kong gateway version 3.7.

You can use 3.8 by specifying it via `values.yaml` if you so desire.

**Comment by pmalek** [comment]
https://github.com/Kong/charts/releases/tag/kong-2.42.0 already ships with 3.7 as default.

You can still set the 3.8 using `values.yaml`. Hope that helps.
