### ISSUE TITLE
Old CRDs in gateway-operator package

### ISSUE THREAD

**Issue by rkuccf** [Kong/charts#1137]
Could I ask for upgrade of CRDs to newest version that contains support to externalTrafficPolicy?

**Comment by pmalek** [comment]
@rkuccf 👋 

https://github.com/Kong/charts/releases/tag/gateway-operator-0.2.2 includes the updated CRDs.

**Comment by rkuccf** [comment]
Thank @pmalek for quick reply. Unfortunately, after installing it operator has issue with cluster permission and is not able to do action on dataplanemetricsextensions:
`
W1015 13:56:50.586784       1 reflector.go:547] pkg/mod/k8s.io/client-go@v0.30.2/tools/cache/reflector.go:232: failed to list *v1alpha1.DataPlaneMetricsExtension: dataplanemetricsextensions.gateway-operator.konghq.com is forbidden: User "system:serviceaccount:operators:controller-manager" cannot list resource "dataplanemetricsextensions" in API group "gateway-operator.konghq.com" at the cluster scope
E1015 13:56:50.586887       1 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.2/tools/cache/reflector.go:232: Failed to watch *v1alpha1.DataPlaneMetricsExtension: failed to list *v1alpha1.DataPlaneMetricsExtension: dataplanemetricsextensions.gateway-operator.konghq.com is forbidden: User "system:serviceaccount:operators:controller-manager" cannot list resource "dataplanemetricsextensions" in API group "gateway-operator.konghq.com" at the cluster scope
`
Could you look at this?

**Comment by pmalek** [comment]
This is fixed in [0.2.3](https://github.com/Kong/charts/releases/tag/gateway-operator-0.2.3) by #1148.

Thanks for staying vigilant 🙇
