### ISSUE TITLE
Helm Hub Listing

### ISSUE THREAD

**Issue by austince** [Kong/charts#114]
Would someone from Kong be willing to accept/ verify a PR in [helm/hub](https://github.com/helm/hub) that added this repo to the listing? It would make the chart(s) here available on [hub.helm.sh](hub.helm.sh).

**Comment by hbagdi** [comment]
You mean this one: https://hub.helm.sh/charts/kong/kong?


You might be running into https://github.com/helm/hub/issues/287

**Comment by austince** [comment]
That's the one! My bad - weird bug!
