### ISSUE TITLE
Separate releases for admin and proxy don't work

### ISSUE THREAD

**Issue by svdubovik** [Kong/charts#124]
Hello, if kong.fullname has .Release.Name and we can't override fullname, integration controller can't connect to svc/RELEASE-kong-proxy which was deployed in other release.

https://github.com/Kong/charts/blob/0896866e1bb5695a51901001b9ccfcd1bfa658d4/charts/kong/templates/_helpers.tpl#L13

**Comment by hbagdi** [comment]
Can you elaborate? What is the integration controller doing in this case?

**Comment by svdubovik** [comment]
Ingress controller uses var 
[CONTROLLER_PUBLISH_SERVICE](https://github.com/Kong/charts/blob/0896866e1bb5695a51901001b9ccfcd1bfa658d4/charts/kong/templates/_helpers.tpl#L181)

Looks like this var should points to [kong-proxy](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/references/cli-arguments.md), but this var includes "kong.fullname" which includes name of the admin-only release.

**Comment by hbagdi** [comment]
You should be able to override it using `ingressController.env` section in the values.yaml file.

**Comment by svdubovik** [comment]
Yes, as workaround it works. I've added `publish_service: kong/proxy-kong-proxy` in `ingressController.env`, but if I rename my release, I should to change this var

**Comment by hbagdi** [comment]
Correct. This is expected because you are maintaining two different releases.
