### ISSUE TITLE
autoscaling/v2beta2 API not being used for autoscaling on HPA

### ISSUE THREAD

**Issue by nikoskip** [Kong/charts#129]
I'm not sure if it's a Kong problem or a Helm problem, but for some reason when I enable the autoscaling feature the HPA template is being rendered using API `autoscaling/v1` and according to `kubectl api-versions` I do have `autoscaling/v2beta2` avaliable on my cluster (I'm using AKS).

```
$ kubectl api-versions | grep autoscaling
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
```
I was checking the HPA template and the condition is very straightforward:

```
apiVersion: {{ .Capabilities.APIVersions.Has "autoscaling/v2beta2" | ternary "autoscaling/v2beta2" "autoscaling/v1" }}
```
It's look like a Helm issue, but I would like to receive some feedback from you before opening an issue on Helm repo.

Helm version: 3.2.0
K8s client version: 1.18
K8s server version: 1.15.10

**Comment by rainest** [comment]
To confirm, do you see this in the template alone, or in the resulting Deployment after it's created and you get it from the server? What version do you see if you run `helm template` against your values.yaml? Are you able to create a v2beta2 HPA manually, without using Helm?

We have a similar report against GKE, where the HPA template renders the correct version, but the resource is converted to v1 once the API server ingests it: https://github.com/Kong/charts/issues/122#issuecomment-618014275

I don't have an AKS system to test with, but am curious if they're doing something similar.

**Comment by nikoskip** [comment]
When I run `helm template` I'm getting the right API version (v2).

I did a test creating a HPA without using Helm and AKS is converting it to v1, just like GKE.

I think there is nothing I can do then.

**Comment by rainest** [comment]
If you have an AKS support contract and can open a case for this, they may be able to provide a workaround or at least further information about why it occurs, and we'd be happy to integrate that into our docs. We don't have a support contract for our test clusters, and I wasn't able to find any conclusive discussion of the issue elsewhere, so we haven't written official of our own.

**Comment by nikoskip** [comment]
Sure. I will contact them and let you know about any information about this issue on AKS.

I will post their answer as soon as they reply.

**Comment by hbagdi** [comment]
Any updates @nikoskip ?

**Comment by nikoskip** [comment]
@hbagdi I sent a support ticket today. I'll let you know any update about it.

**Comment by nikoskip** [comment]
Azure contact me back and according to their reply this behavior is expected. I'm going to quote a reply from [the same issue that we are talking about here but on the Kubernetes repo](https://github.com/kubernetes/kubernetes/issues/71556):

> This is working as intended. v1 is the default version of HPA so that's what you get if you don't request a specific version. You can get autoscaling/v2beta1 representation of your HPA by running `kubectl get hpa.v2beta1.autoscaling -o yaml hpa-demo`
> 
> A bit of explanaition: Internally all HPA objects are stored in the same way, regardless which version of API you used to create them. When you get HPA Kubernetes API server converts this internal representation to the version you requested.

As this is expected behavior by design, I'm going to close this issue because is not a Kong or Helm bug.

**Comment by anantvardhan04** [comment]
@nikoskip Just wanted to know, if this is only the representation part which gets altered or the expected behavior of autoscaling/v2beta1 API would also be obstructed ? As in my case, I have set the target for memory metrics as well, but pods are not scaling out even when the memory utilization has passed the target threshold.

**Comment by hbagdi** [comment]
@anantvardhan04 Please open a new issue or rather use our community forum: https://discuss.konghq.com.

**Comment by harshmanvar** [comment]
if you are on GKE and facing issue where enabled API are

    autoscaling/v1
    autoscaling/v2beta1

while GKE version is around `1.12 to 1.14` you wont be able to apply manifest of `autoscaling/v2beta2` however you can apply same thing something like 

    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    metadata:
      name: core-deployment
      namespace: default
    spec:
      maxReplicas: 9
      minReplicas: 5
      scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: core-deployment
      metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageValue: 500m

if you want based on utilization 


        apiVersion: autoscaling/v2beta1
        kind: HorizontalPodAutoscaler
        metadata:
          name: core-deployment
          namespace: default
        spec:
          maxReplicas: 9
          minReplicas: 5
          scaleTargetRef:
            apiVersion: extensions/v1beta1
            kind: Deployment
            name: core-deployment
          metrics:
          - type: Resource
            resource:
              name: cpu
              targetAverageUtilization: 80
