### ISSUE TITLE
How to deploy two sets of non-interfering kong on a k8s cluster？

### ISSUE THREAD

**Issue by yangbin1212** [Kong/charts#133]
I have a k8s cluster, and dev env, test env, and prod env are deployed on the cluster. Now I want to use a kong for dev and test env, and another kong for prod. How to deploy？

**Comment by hbagdi** [comment]
> I have a k8s cluster, and dev env, test env, and prod env are deployed on the cluster.

This is generally not recommended for Kubernetes clusters. You should have isolated clusters.


> Now I want to use a kong for dev and test env, and another kong for prod. How to deploy？

What have you tried? What problems did you run into?

**Comment by yangbin1212** [comment]
> > I have a k8s cluster, and dev env, test env, and prod env are deployed on the cluster.
> 
> This is generally not recommended for Kubernetes clusters. You should have isolated clusters.
> 
> > Now I want to use a kong for dev and test env, and another kong for prod. How to deploy？
> 
> What have you tried? What problems did you run into?

I tried to deploy two sets of the same kong, but the second set could not create crds, and the second set could not be used when the first set was deleted. I want my dev environment and prod environment to use different kong, but currently these environments are deployed on a k8s

**Comment by yangbin1212** [comment]
The two sets of kong are not isolated, I can use any combination of IP and port to access the services and routes I added

**Comment by hbagdi** [comment]
> I tried to deploy two sets of the same kong, but the second set could not create crds, and the second set could not be used when the first set was deleted. I want my dev environment and prod environment to use different kong, but currently these environments are deployed on a k8s

Yes this is a pain point currently. You will have to install CRD only once in the first release and then disable installing CRDs in other releases.

>The two sets of kong are not isolated, I can use any combination of IP and port to access the services and routes I added

You need to use `kubernetes.io/ingress.class` annotation to seggregate configuration of two different classes.

**Comment by yangbin1212** [comment]
> > I tried to deploy two sets of the same kong, but the second set could not create crds, and the second set could not be used when the first set was deleted. I want my dev environment and prod environment to use different kong, but currently these environments are deployed on a k8s
> 
> Yes this is a pain point currently. You will have to install CRD only once in the first release and then disable installing CRDs in other releases.
> 
> > The two sets of kong are not isolated, I can use any combination of IP and port to access the services and routes I added
> 
> You need to use `kubernetes.io/ingress.class` annotation to seggregate configuration of two different classes.

Thank you for your answer, I will try the solution you said, now I close this issue
