### ISSUE TITLE
Upgrade chart to use Kong 2.0

### ISSUE THREAD

**Issue by oscarlofwenhamn** [Kong/charts#14]
Current default appears to be 1.4:
https://github.com/Kong/charts/blob/b1131b662d0d81248ca03c781e0609a1cbc66288/charts/kong/values.yaml#L38

It is understandable that this might not be top priority for the chart, but it should be done sooner or later.

**Comment by hbagdi** [comment]
Thanks for the nudge!
We will be bumping up in a few weeks. You can easily bump it for yourself by using a custom values file or using `--set` flag.

**Comment by oscarlofwenhamn** [comment]
Brilliant, cheers! Any breaking changes that you know can influence the chart, or is it compatible with 2.0 in the current state?

**Comment by hbagdi** [comment]
The current chart is compatible with 2.0.
Kong 2.0 does not have any breaking changes.

**Comment by OmriHarary** [comment]
@hbagdi Will the new version of the chart including 2.0 by default include support for configuring the new status interface and using it with readiness/liveness probes and the ServiceMonitor?

**Comment by hbagdi** [comment]
> new status interface and using it with readiness/liveness probes and the ServiceMonitor?

Not yet. We have not moved to the new Status interface yet because there is still a significant userbase which is running Kong 1.3 and below versions, which don't have the status interface. You can easily tweak the configuration of probes to use status interface.

And non-breaking changes (totally possible) for status interface support to this chart are welcome!

**Comment by OmriHarary** [comment]
> there is still a significant userbase which is running Kong 1.3 and below versions

That makes sense, thanks for explaining.


> And non-breaking changes (totally possible) for status interface support to this chart are welcome!

I'll see what I can put together, and be sure to contribute it if it's any good.

**Comment by rainest** [comment]
Version 1.3.0 of the Kong chart is [now released](https://github.com/Kong/charts/releases/tag/kong-1.3.0), resolving this issue.
