### ISSUE TITLE
Write readme stuff for Helm 2 deprecation

### ISSUE THREAD

**Issue by hbagdi** [Kong/charts#143]
Helm 2 is now deprecated and the recommended version is Helm 3.
We need to announce Helm 2 is deprecated for our chart and update our documents to use Helm 3 by default.

**Comment by rainest** [comment]
https://github.com/Kong/charts/pull/251 is the last remaining breaking change I wanted to get in before 2.0. That PR still includes support for legacy proxy and admin stuff, so it will be released in 1.x and should be available for a couple months before we remove all deprecated stuff (features with NOTES.txt warnings) entirely in 2.x.

Helm does not provide information about its version to the template engine, so we can't add a Helm 2 deprecation warning inside the chart itself; that will only be announced in the changelog. We furthermore don't have immediate plans to make changes that will break Helm 2 support, as templated CRDs will remain (they're necessary for CRD-only releases), albeit defaulted to false. We can [use the new Chart.yaml format](https://helm.sh/docs/faq/#chartyaml-apiversion-bump), which is only supported by Helm 3, but there's no pressing reason to do so.

**Comment by rainest** [comment]
https://github.com/Kong/charts/pull/258 covers the remaining deprecations we want in place before the cutover.

**Comment by mflendrich** [comment]
remaining work: #260
