### ISSUE TITLE
[kong] NOTES.txt warnings include extra newlines

### ISSUE THREAD

**Issue by rainest** [Kong/charts#144]
The NOTES.txt template may include one or more [warnings](https://github.com/Kong/charts/blob/kong-1.5.0/charts/kong/templates/NOTES.txt#L13-L33) if performing an upgrade or install with deprecated configuration in values.yaml. Because of limitations in template newline chomping, this can print excess newlines.

Based on review of other charts, we can avoid this by moving string generation into a helper template that builds the complete text with string concatenation rather than templating each warning individually.

**Comment by mflendrich** [comment]
Fix was made as a commit on the 1.12.0 release PR. No individual PR for this fix.
