### ISSUE TITLE
Add support for fullnameOverride to Chart

### ISSUE THREAD

**Issue by timduhenchanter** [Kong/charts#157]
Add support for fullnameOverride in the `kong.fullname` define in _helpers.tpl

**Comment by hbagdi** [comment]
Is this something that aligns with guidelines for charts from the maintainers of Helm?

**Comment by timduhenchanter** [comment]
https://github.com/helm/charts/blob/master/stable/ambassador/templates/_helpers.tpl#L14

This is typically the condition I have found to support this.  It avoids duplication of named entries for `...metadata.name` in the event that you do not use multiple release names and maybe has other uses than the one I just highlighted.  I don't know if this is officially sanctioned as part of a Helm standard but I find that it is available for a majority of charts.

**Comment by hbagdi** [comment]
I see. @rainest how do you feel about adding yet another knob for this?

**Comment by rainest** [comment]
Yeah that's reasonable to add--just today ran into someone confused as to why resources got named `kong-kong-whatever` when they named their release `kong`. I'd recommend still having some sort of indicator showing the purpose of a release (e.g. "prod", "test", etc. for the environment type; "dmz", "internal" for the network zone; etc.), but those can often be handled via other means.

Marked "good first issue" as this should be simple to add if someone in the community is interested. We should create it if we don't see any community submissions, though it's not an immediate priority.

**Comment by danielcrisap** [comment]
I used Release Name for identification across all cluster about my applications and using `fullname` on Kong chart don't remove the prefix of `Release.Name`.
In https://github.com/Kong/charts/blob/main/charts/kong/templates/_helpers.tpl#L11-L18

Would be great if we have a way to fully override the name of resources that will be created in some release.

**Comment by shaneutt** [comment]
Closing this as stale as there has not been activity in nearly a year. If you're still interested in this functionality please feel free to comment and we'll be happy to re-open this and re-assess.

**Comment by randmonkey** [comment]
re-open this for related FTI: https://konghq.atlassian.net/browse/FTI-4075
