### ISSUE TITLE
[kong] separate README.md into multiple guides

### ISSUE THREAD

**Issue by rainest** [Kong/charts#164]
README.md is long and ever-growing. Many sections are somewhat specialized, and README.md would benefit from being reduced to a shorter discussion of basic usage with links to other references for details and advanced topics.

The [ingress controller documentation](https://github.com/Kong/kubernetes-ingress-controller/tree/master/docs) is a good model, where there are several types of documents (references for, well, reference, concepts for high-level explanation, guides for step-by-step instructions for specific tasks) linked from README.md.

**Comment by shaneutt** [comment]
Closing as stale, if we still feel we need this change let's re-open this.
