### ISSUE TITLE
RBAC Issues Kong Helm Chart v1.0.0

### ISSUE THREAD

**Issue by jlentzfl** [Kong/charts#17]
Kong configured as db-less with Kong Ingress Controller enabled.

Kong Chart version: 1.0.0

The ingress-controller logs are full of RBAC errors for both K8 objects and the Kong CRDs:

 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Unauthorized
reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.KongConsumer: Unauthorized

leaderelection.go:324] error retrieving resource lock kong-internal/kong-ingress-controller-leader-kong-kong: Unauthorized

I know there's an existing issue #9 that will fix a number of typos.  I believe I've found another one. 
In the _helpers.tpl kong.controller-container definition, the election-id argument is configured as:

--election-id=kong-ingress-controller-leader-{{ .Values.ingressController.ingressClass }}
which becomes --election-id=kong-ingress-controller-leader-kong

while the controller-rbac-resources.yaml sets the Role configmap resource name as:

- "kong-ingress-controller-leader-{{ .Values.ingressController.ingressClass }}-{{ .Values.ingressController.ingressClass }}"
which becomes  kong-ingress-controller-leader-kong-kong with no changes to .Values.ingressController.ingressClass.

Perhaps a fix for the leader election id could be added to #9?  I'm hoping the resolution of all the typos will fix the RBAC issues.

**Comment by hbagdi** [comment]
Can you please try 1.0.3 version of the chart that was just released?

**Comment by jlentzfl** [comment]
I'll give it a try when I get the thumbs up from our dev team.  They need everything to remain stable for a few days following a large release.

**Comment by jlentzfl** [comment]
Tried deploying 1.1.1 helm chart just now.  Had to first helm delete --purge the previous 1.0.0 release. Deployment failed with:
Error: parse error in "kong/templates/_helpers.tpl": template: kong/templates/_helpers.tpl:465: function "mergeOverwrite" not defined

Helm v2.12.3

**Comment by hbagdi** [comment]
It seems like Helm v2.12.3 doesn't include the function.

The function was introduced in Sprig library in 2.18: 
https://github.com/Masterminds/sprig/blob/master/CHANGELOG.md#release-2180-2019-02-12

Helm 2.12.3 uses 2.16 version of the library:
https://github.com/helm/helm/blob/v2.12.3/glide.yaml#L15

Can you please upgrade Helm?

**Comment by jlentzfl** [comment]
Upgraded helm to v2.16.1 and was able to install the Kong 1.1.1 helm chart successfully!  Also, I've seen no "Failed to list" messages with this chart.

Thank you for the fix!
