### ISSUE TITLE
make GH Pages track `main` not `master`

### ISSUE THREAD

**Issue by mflendrich** [Kong/charts#178]
Following #177, GH Pages behind https://charts.konghq.com/ needs to track `main` and not `master`.

context: https://github.com/Kong/charts/pull/177#issuecomment-668107229

assigning @hbagdi because editing GH Pages config requires elevated permissions.

**Comment by hbagdi** [comment]
I don't think I understand what needs to be done here.
Github pages are built using the gh-pages branch.

**Comment by mflendrich** [comment]
Ah. i didn’t know if it followed gh-pages or master but I wanted to stay on the safe side.

Nothing to do then.
