### ISSUE TITLE
[kong] upgrade manifests using deprecated APIs (RBAC, CRD)

### ISSUE THREAD

**Issue by mflendrich** [Kong/charts#183]
Some k8s APIs which we the kong chart uses today (see the issue linked above) are getting disabled in k8s v1.22, so we need to upgrade our templates so that they continue to apply successfully in k8s v1.22 and beyond.

Same as Kong/kubernetes-ingress-controller#801 but the scope of this issue is updating the templates included in the chart.

**Comment by jbouzekri** [comment]
+1

**Comment by hbagdi** [comment]
With our manifests in the controller repository, we do not worry about lifecycles but for charts we do care.
Let's say we do bump these versions, would changes cleanly apply to existing installations? Would doing `helm upgrade` cause failures?

**Comment by rainest** [comment]
As of 2.4, these have been upgraded.
