### ISSUE TITLE
Is there a reason why some templates does not contain namespace?

### ISSUE THREAD

**Issue by mdostal-hci** [Kong/charts#192]
Hello,

is there a reason why some of the templates (e.g. `service-kong-admin`, `service-kong-proxy`) do not contain namespace (I would expect something like `namespace: {{ .Release.Namespace }}` in template) whereas others (`controller-service-account`) do? 

When using `helm template` with this chart to generate manifests, namespaces are not present which complicates further usage. It would be nice to have them for all the templates (I can prepare a PR if needed).

Regards,
Martin.

**Comment by hbagdi** [comment]
Helm adds the namespace even if the template doesn't contain `namespace: {{ .Release.Namespace }}`, hence it is not required in templates.

It seems you want to generate the YAML from Helm and then use it. We should have no problem in accepting a PR to accommodate your workflow.

**Comment by mdostal-hci** [comment]
Exactly - I use generated manifests in my workflow not by Helm, so I need namespace to be explicitly defined. PR is attached, thank you.

**Comment by rainest** [comment]
Closed following #193. Not released as of yet, but will be in the next release.
