### ISSUE TITLE
How can i mount extra volume from host to Kong Pod using this helm chart ?

### ISSUE THREAD

**Issue by jshahv** [Kong/charts#196]
We want to put logs generated by Kong pod into one volume (external storage mounted on host).  I understand best practice is to have log on stdout and stderr then ship it to some external logs tool like elastic but for now our appliacation needs log at mounted storage. any help for this issue appriciated

**Comment by rainest** [comment]
As-is, we have a volume mount system that's used for a couple specific tasks (mounting plugin code and some additional NGINX configuration). The relevant section of the template is https://github.com/Kong/charts/blob/kong-1.10.0/charts/kong/templates/_helpers.tpl#L243-L335

That could be expanded to support arbitrary volume mounts, i.e. something along the lines of "provide a volume name, type, and mount point+permissions, and the chart will make it appear there. We'd be happy to accept a PR that adds that, but don't currently have plans to add it ourselves.

**Comment by mikemenaker** [comment]
I'll try and take a swing at this.

**Comment by mikemenaker** [comment]
@rainest should I create the pull request on a branch of the next branch directly or on a fork?

I have the code ready but got access denied pushing my branch.

**Comment by ghost** [comment]
Although @mikemenaker effort is valuable, Important part is attaching a volume to kong pod not a Configmap. An example use case might be creating volume for proto files for grpc-to-rest conversion. 

Without volumes, we need to use configmap to mount these files which is easy for a single proto. But when it comes to directory structure(google-common-protos), it's painful to create represent this directory structure with current configmap --from-file flag.

**Comment by hbagdi** [comment]
Please feel free to open another issue for your use case, @AliArdaOrhan!
We will happily accept a PR for it.
