### ISSUE TITLE
plain scalar cannot be used when setting nginx directives

### ISSUE THREAD

**Issue by sanyer** [Kong/charts#198]
Using plain scalar for nginx directives converts it to value not supported by nginx:

so,
```yaml
nginx_http_tcp_nodelay: "on"
nginx_http_tcp_nodelay2: on
```
becomes
```yaml
- name: KONG_NGINX_HTTP_TCP_NODELAY
    value: "on"
- name: KONG_NGINX_HTTP_TCP_NODELAY2
    value: "true"
```

and `wait_for_db` container shows this error:
```
waiting for db
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:37: nginx configuration is invalid (exit code 1):
nginx: [emerg] invalid value "true" in "tcp_nodelay" directive, it must be "on" or "off" in /kong_prefix/nginx-kong.conf:38
nginx: configuration file /kong_prefix/nginx.conf test failed
```

**Comment by hbagdi** [comment]
I'm not sure why this is happening. A string `on` should be rendered correctly. @rainest, any clue?

**Comment by rainest** [comment]
I agree that it probably should, or that if nothing else the current system results in a great deal of confusion despite its ability to handle several different commonly-used on/off true/false yes/no conventions without changing them to fit something more explicit :smile: 

Sadly, nothing we can do here, it's YAML's fault: https://yaml.org/type/bool.html or https://hitchdev.com/strictyaml/why/implicit-typing-removed/ if you want a more humorous discussion. Quoting the string is necessary here.

**Comment by sanyer** [comment]
oh, ok
at least it should be mentioned i the docs then
