### ISSUE TITLE
helm delete doesn't remove jobs

### ISSUE THREAD

**Issue by aaronhmiller** [Kong/charts#203]
ran a `helm delete controlplane -n cp`
expecting everything installed by the chart to be removed, but found this hanging around:
```
kubectl get jobs -n cp
NAME                                       COMPLETIONS   DURATION   AGE
controlplane-kong-init-migrations          0/1           26m        26m
controlplane-kong-pre-upgrade-migrations   0/1           10m        10m
```
Had to do a `kubectl delete jobs controlplane-kong-init-migrations controlplane-kong-pre-upgrade-migrations` to get things cleaned up.

**Comment by rainest** [comment]
That's expected. The migration jobs are handled via hooks, which create resources that aren't managed by the release, so deleting the release does not delete them. Looks kinda odd when you see it, I'll admit, but that's how Helm works :woman_shrugging: 

We use the default `before-hook-creation` [deletion policy](https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies), so they're normally deleted upon the next job of the same sort. That's kinda what we want for the upgrade jobs on the off-chance there's something you want to inspect in their logs, as leaving them around after completion doesn't really cause any harm--there's only ever one of each per release, so they at least don't balloon infinitely.

Kubernetes has a [TTL mechanism](https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs) that would allow us to strike a good middle ground between keeping the logs around for inspection and discarding them after they're unlikely to be useful (e.g. after 3 days or so). However, that's been stuck in beta forever for whatever reason, with the upshot that managed providers often don't support it.

On our long-term radar, but it's mostly a cosmetic thing, so I'm fine waiting til the ideal K8S-native solution comes out of beta.
