### ISSUE TITLE
Dbless config map auto-reload

### ISSUE THREAD

**Issue by yasharya1984** [Kong/charts#217]
Is there any way to soft reload kong when config map is updated ? kong.yml declarative config file is kept in configMap. I am using helm charts for the deployment.  
Do i have to update deployment.yaml and add some annotation for sha256 OR it is there any other way ?  For annotation, is there any document to help with that ?

**Comment by mirkoszy** [comment]
I am using reloader to recreate kong pods when kong config, stored in configmap, changes. 

https://github.com/stakater/Reloader

**Comment by pmalek** [comment]
Hi @yasharya1984 👋 

As mentioned by @mirkoszy: you can use an off the shelf tool like Reloader for this if you're storing the config in a ConfigMap.

I'm not even sure if there is a mechanism to access a ConfigMap or a Secret from helm to check its annotations/contents during upgrade/install 🤔.

Feel free to reach us if you feel this can be resolved differently. I'm closing this for now.
