### ISSUE TITLE
[kong] update default worker count to 2

### ISSUE THREAD

**Issue by hbagdi** [Kong/charts#227]
The Helm chart sets `nginx_worker_processes: "1"`. The original motivation for this default, against the kong default of `auto` was users seeing resource exhaustion when they installed Kong. This usually happened with k8s worker nodes containing a larger number of CPUs/vCPUs.
With the default of `1`, we run into the other problem where a lot of users run into severe performance problems, especially with KIC DB-less deployments, where a sync (POST /config) request can introduce significant latencies on proxy requests.
Given the number of external and internal reports on this specific, we should update the default value to `2`.

TODO:
- [ ] Update the default value to 2 in this repository
- [ ] Update the default value to 2 in Kong Ingress Controller's [repository](https://github.com/Kong/kubernetes-ingress-controller/blob/3a72f85f3baca0e630b2c117896136b34c10e2c3/hack/dev/dbless/base/kong.yaml#L26)

**Comment by mflendrich** [comment]
What is the resource consumption impact of this change?

**Comment by mflendrich** [comment]
Suggest in update instructions that users override the new default with 1 if they encounter OOM after updating.
