### ISSUE TITLE
[kong] change worker_consistency to `eventual`

### ISSUE THREAD

**Issue by hbagdi** [Kong/charts#228]
Kong's default for `worker_consistency` is `strict`.
For the dynamic nature of k8s and especially with KIC frequently updating Kong's configuration, `strict` worsens Kong's performance. Also, k8s users are usually familiar with eventually consistent nature of all infrastructure components.

Todo:
- [ ] Update the default value to 2 in this repository
- [ ] Update the default value to 2 in Kong Ingress Controller's repository

**Comment by bungle** [comment]
I agree, changing this for `3.0.0 (in Kong)` would be good default OR dropping the `strict` behavior altogether (might need more work on test suite). Could KIC change the default before that?

**Comment by mflendrich** [comment]
This is a default that makes more sense to change in Kong rather than in the Helm chart. Also, given the changes happening to the worker config propagation model in 3.0, this becomes obsolete.
