### ISSUE TITLE
how to install kong with admin and postgres 

### ISSUE THREAD

**Issue by sany98215** [Kong/charts#239]
when I install kong with this shell
```
helm install kong/kong --name kong --set ingressController.enabled=true --set admin.type=LoadBalancer --set proxy.type=LoadBalancer --set admin.enabled=true --set env.database=postgres --set env.pg_database=kong --set env.pg_user=kong --set env.pg_password=kong --set postgresql.enabled=true
```
and got an Error :
```
# kubectl logs kong-kong-init-migrations-p7z8h
Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: FATAL: password authentication failed for user "kong"

  Run with --v (verbose) or --vv (debug) for more detail
```
I want to install kong with db , what shoud i do？

**Comment by claudm** [comment]
helm upgrade --install kong kong/kong  --set ingressController.installCRDs=false --set service.tls.enabled="false" --set postgresql.enabled=true   --set admin.http.enabled=true  --set admin.http.enabled=true  --set postgresql.postgresqlUsername=kong --set  postgresql.postgresqlPassword=kong  --set postgresql.postgresqlDatabase=kong   --set admin.enabled=true --set ingressController.enabled=true   --set admin.type=LoadBalancer --set proxy.type=LoadBalancer  --set proxy.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-internal"=0.0.0.0/0  --set admin.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-internal"=0.0.0.0/0 --set env.database=postgres --set env.pg_user=kong --set env.pg_password=kong --set  env.pg_database=kong --set admin.enabled=true
