### ISSUE TITLE
how can i change log format?

### ISSUE THREAD

**Issue by RobertoHuang** [Kong/charts#241]
I want to change default log farmat? how can i do?

**Comment by RobertoHuang** [comment]
extraConfigMaps:
  - name: kong-server-nginx
    mountPath: /kong_prefix/nginx.conf
    subPath: nginx.conf

I try to use my custom nginx.conf override the default nginx.conf,  here is my configmap define:

apiVersion: v1
data:
  nginx.conf: |+
    pid pids/nginx.pid;
    error_log /dev/stderr notice;

    # injected nginx_main_* directives
    daemon off;
    worker_processes 2;
    worker_rlimit_nofile 16384;

    events {
        # injected nginx_events_* directives
        multi_accept on;
        worker_connections 16384;
    }

    http {
        include 'nginx-kong.conf';
    }
kind: ConfigMap
metadata:
  name: kong-server-nginx
  namespace: kong

After those， the pod status always 
![image](https://user-images.githubusercontent.com/20842825/102218160-86e74300-3f18-11eb-92d1-c5ca67f02e81.png)

and it doesn't have any log output
![image](https://user-images.githubusercontent.com/20842825/102218238-a3837b00-3f18-11eb-9a64-54daa43d2e0e.png)

**Comment by rainest** [comment]
Not sure what's breaking in the custom config (you'd need to check those Pods' logs to see exactly what's preventing startup), but in any case you don't need a custom configuration file here. Using directive injection [allows you to define a custom format and override the standard log from environment variables](https://discuss.konghq.com/t/custom-access-logs-format/4580/5).

For Helm, you'll set `env.proxy_access_log: /dev/stdout custom_fmt` in values.yaml to set the `KONG_PROXY_ACCESS_LOG` variable (and so on for the rest).

Does that work for you?
