### ISSUE TITLE
Installation failed: using helm3

### ISSUE THREAD

**Issue by bkumar0801** [Kong/charts#244]
I was trying to install Kong 2.2(latest) in my AKS cluster (Kubernetes 1.17.13) using helm.

I am getting this error,

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[1].livenessProbe): unknown field "enabled" in io.k8s.api.core.v1.Probe, ValidationError(Deployment.spec.template.spec.containers[1].readinessProbe): unknown field "enabled" in io.k8s.api.core.v1.Probe, ValidationError(Deployment.spec.template.spec.securityContext): unknown field "enabled" in io.k8s.api.core.v1.PodSecurityContext]

Could someone here guide me on what is the issue? @hbagdi

**Comment by mflendrich** [comment]
@bkumar0801,

At first glance it seems that your `values.yaml` contains `enabled: true|false` under `readinessProbe` and `livenessProbe`, which is not correct. You need to specify a [Probe](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#probe-v1-core).

For example - see the [defaults in our `values.yaml`](https://github.com/Kong/charts/blob/4f433dde832873dfc325f179bcadfe74db326d08/charts/kong/values.yaml#L351)

If you want to disable readiness/liveness probes (which I strongly recommend against), the right YAML to override the default is
`readinessProbe: null` and `livenessProbe: null`. See [Deleting a default key](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key) in Helm documentation.

Closing this issue for now. If this doesn't solve the problem, please post your
- helm version,
- helm chart version,
- `values.yaml` contents.
