### ISSUE TITLE
 Helm2 Kong install fail

### ISSUE THREAD

**Issue by gogovan-vincentngai** [Kong/charts#261]
**Issue**
Install Kong with default cli fail 

**Expected**
Install under helm tiller

**Actual**
Fail return with service-kong-proxy.yaml:16: illegal number syntax: "-"

**Config**
GKE Cluster : v1.17.14-gke.400
Helm Version : v2.13.1
Kong Chart version : 2.2

**Detail**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-gke.400", GitCommit:"b00b302d1576bfe28ae50661585cc516fda2227e", GitTreeState:"clean", BuildDate:"2020-11-19T09:22:49Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

$ helm version --tiller-namespace infra-helm-tiller
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

$ helm search kong/kong
NAME     	CHART VERSION	APP VERSION	DESCRIPTION
kong/kong	1.14.0       	2.2        	The Cloud-Native Ingress and API-management

$helm install kong/kong --name konggw  --dry-run --debug --namespace kong --tiller-namespace infra-helm-tiller

[debug] Created tunnel using local port: '49844'
[debug] SERVER: "127.0.0.1:49844"
[debug] Original chart version: ""
[debug] Fetched kong/kong to /Users/XXX/.helm/cache/archive/kong-1.14.0.tgz
[debug] CHART PATH: /Users/XXXX/.helm/cache/archive/kong-1.14.0.tgz
Error: parse error in "kong/templates/service-kong-proxy.yaml": template: kong/templates/service-kong-proxy.yaml:16: illegal number syntax: "-"

```

Anyone ?

**Comment by gogovan-vincentngai** [comment]
After i mofiy the file **service-kong-proxy.yaml**  as below and using local chart , it seems pass 
but it just does not make sense 
```
{{- if .Values.deployment.kong.enabled }}
{{- if .Values.enterprise.enabled }}
{{- if and .Values.proxy.enabled (or .Values.proxy.http.enabled .Values.proxy.tls.enabled) -}}
{{- $serviceConfig := dict -}}
{{- $serviceConfig := merge $serviceConfig .Values.proxy -}}
{{- $_ := set $serviceConfig "fullName" (include "kong.fullname" .) -}}
{{- $_ := set $serviceConfig "namespace" (include "kong.namespace" .) -}}
{{- $_ := set $serviceConfig "metaLabels" (include "kong.metaLabels" .) -}}
{{- $_ := set $serviceConfig "selectorLabels" (include "kong.selectorLabels" .) -}}
{{- $_ := set $serviceConfig "serviceName" "proxy" -}}
{{- include "kong.service" $serviceConfig }}
{{ if .Values.proxy.ingress.enabled }}
---
{{ include "kong.ingress" $serviceConfig }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}

```

**Comment by rainest** [comment]
Do you still see this issue on the latest 1.14.x release? There were some issues with the placement of if blocks in the initial release.

The issue associated with https://github.com/Kong/charts/commit/b9f917b90702d8f61ceb5ad4d94bd61fdcfeb495 doesn't look identical, but it's in the same area.

If that doesn't fix the issue, can you provide us [the proxy section from your values.yaml](https://github.com/Kong/charts/blob/kong-1.14.5/charts/kong/values.yaml#L169-L234) and output from `helm template`? The Helm error doesn't show the problem line, but the template output should let us see it.

Also do note that we've deprecated Helm 2 support, and will make changes that break it in the near future (within a month or so). While this issue doesn't look like it's related to that, you should look at upgrading to Helm 3 as soon as possible.

**Comment by rainest** [comment]
Does the change in https://github.com/Kong/charts/issues/313 also fix this for you? Still unclear why I can't replicate this (unlike that issue, you _are_ using the Helm client), but if that addresses it we can probably apply that change as a hotfix to the 1.15 series--unlike the fix proposed here, that change doesn't remove the legacy handler logic.
