### ISSUE TITLE
How to set password from secrets ? (when external database)

### ISSUE THREAD

**Issue by TOTOleHero** [Kong/charts#274]
Hello, 

I want to use external secrets in env block ?

```
...
env:
  database: "postgres"
  ...
  pg_user: valueFrom: secretKeyRef:  name: kong-secrets key: db-user
  pg_password: valueFrom: secretKeyRef:  name: kong-secrets key: db-user
  ...
```

Thanks you 

In chart template there is no way to use secrets :(, why this restriction ?

```
...
{{- $userEnv := dict -}}
{{- range $key, $val := .Values.env }}
  {{- $upper := upper $key -}}
  {{- $var := printf "KONG_%s" $upper -}}
  {{- $_ := set $userEnv $var $val -}}
{{- end -}}
...
```

**Comment by rainest** [comment]
You can, you'll just need to indent them as you normally would. https://github.com/Kong/charts/blob/main/charts/kong/README.md#the-env-section shows an example

The multiline secretKeyRef block will be preserved in the `$val` variable in that template segment, and will later be rendered in the Deployment's env block. The template there only modifies the key, to properly format it into a `KONG_WHATEVER` environment variable.
