### ISSUE TITLE
q: why is ingress controller and db-less mutually exclusive?

### ISSUE THREAD

**Issue by naseemkullah** [Kong/charts#284]
Hello, I am trying to setup kong as an ingress controller in db-less mode though the concepts seem to be mutually exclusive in [this chart](https://github.com/Kong/charts/blob/4186fda4ce6729dcfacb03761106cc4c88893729/charts/kong/values.yaml#L284-L285) but not according to [docs](https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/concepts/deployment/#without-a-database). Is this expected?

**Comment by naseemkullah** [comment]
Seems like I could leverage the CRDS + k8s secrets to achieve the desired config fortunately!

**Comment by rainest** [comment]
To clarify, DB-less _mode_ (setting `env.database = off`) is compatible with the controller. The DB-less config file loader in values.yaml is not.

When the controller is enabled, it's responsible for updating DB-less config through the Kong admin API's `/config` endpoint. It generates this configuration from Kubernetes resources and loads it automatically.

The DB-less config file is an alternate means of loading a static DB-less configuration (not generated from Kubernetes resources). It's loaded at startup, but any `POST /config` request after will update the configuration Kong uses--the controller will override anything you place in that file more or less immediately after Kong starts.
