### ISSUE TITLE
Pre-release chart 2.0-preview.1

### ISSUE THREAD

**Issue by mflendrich** [Kong/charts#299]
Problem: current releaser would update the "latest", therefore upgrading users unexpectedly to this preview version.

The scope of this issue is to release the preview version in a way that won't affect users who don't install this version explicitly.

**Comment by rainest** [comment]
Blocked by #304. We either need a safe way of handling existing managed CRDs with a changed default or (less ideal) accept that you'll still need to explicitly set `installCRDs=false` on new installs.

Blocked by #301.
