### ISSUE TITLE
[kong] Release chart 2.0 GA on April 13th

### ISSUE THREAD

**Issue by mflendrich** [Kong/charts#309]
Release only if there were no bugs found in 2.0.0-rc.2 that would necessitate an rc.3.

~Blocked by #301 #304~

~This is to happen after https://github.com/Kong/charts/issues/299~

**Comment by mflendrich** [comment]
No longer blocked - the blockers are merged in now.

2.0 GA release is due 2 weeks after 2.0.0-rc.1.

**Comment by navaati** [comment]
Hi guys. I’m kinda sorry to ruin the party so close to the release but can you take a look at that: https://github.com/Kong/charts/issues/322. It’s a regression of 2.0.0-rc.1 happenning on older clusters.

**Comment by mflendrich** [comment]
~Blocked by #322 and release of 2.0.0-rc.2~
