### ISSUE TITLE
Chart broken on Kubernetes <1.16 due to lookup using apiextensions.k8s.io/v1 CRD

### ISSUE THREAD

**Issue by navaati** [Kong/charts#322]
Hi.

When using the chart with a cluster in version 1.15, the helm install fails with this error message:
```
lookup_func.go:111: [ERROR] unable to retrieve resource list for: apiextensions.k8s.io/v1 , error: the server could not find the requested resource
lookup_func.go:85: [ERROR] unable to get apiresource from unstructured: apiextensions.k8s.io/v1, Kind=CustomResourceDefinition , error the server could not find the requested resource
Error: template: kong/templates/custom-resource-definitions.yaml:21:25: executing "kong/templates/custom-resource-definitions.yaml" at <lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "kongplugins.configuration.konghq.com">: error calling lookup: unable to get apiresource from unstructured: apiextensions.k8s.io/v1, Kind=CustomResourceDefinition: the server could not find the requested resource
```
This is using Helm 3.3.4, the last version of Helm compatible with the cluster.

The cause of the error is here https://github.com/Kong/charts/blob/kong-2.0.0-rc.1/charts/kong/templates/custom-resource-definitions.yaml#L21, directly using the `apiextensions.k8s.io/v1` API without first checking its availability.

The chart advertises compatibility with Kube 1.12+ so it looks like a bug :).

**Comment by mflendrich** [comment]
Thanks @navaati for this bug report.

The helm chart CRDs are apiextensions.k8s.io/v1beta1 which should be compatible with <1.16. It's just the `lookup()` check that tries to talk to the k8s api in terms of v1 CRDs, which breaks it.

We're going to fix that lookup() check and then release a `2.0.0-rc.2` before 2.0 GA.

> The chart advertises compatibility with Kube 1.12+ so it looks like a bug :)

The statement in README.md about 1.12+ is unfortunate. We're definitely going to adjust it. After all, it's at odds with KIC's [compatibility matrix](https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/references/version-compatibility/#kubernetes).

**Comment by navaati** [comment]
Ah, a valuable link, this compatibility matrix. Glad to see the target is 1.14 (I was slightly worried the "fix" to the bug would be to bump the requirement of the chart to 1.16, which would be fair but inconvenient for me ^^).

Thanks a lot for handling this ! Hoping 2.0.0-rc.2 will be the one :crossed_fingers: !

**Comment by rainest** [comment]
Initial review suggested that we may be able to just use v1beta1 in the check, but we can't while still handling newer versions. Although the CRDs we include in the chart are still `apiextensions.k8s.io/v1beta1`, Kubernetes will automatically promote them to `v1` for you as of the first version that supports it (1.16):

```
$ cat crds/custom-resource-definitions.yaml| grep apiV   
apiVersion: apiextensions.k8s.io/v1beta1
...

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2021-01-22T22:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl create -f crds/custom-resource-definitions.yaml            
customresourcedefinition.apiextensions.k8s.io/kongplugins.configuration.konghq.com created
...

$ kubectl get crd kongplugins.configuration.konghq.com -o yaml | grep apiV
apiVersion: apiextensions.k8s.io/v1
```

**Comment by mflendrich** [comment]
@rainest 

> Kubernetes will automatically promote them to v1 for you as of the first version that supports it (1.16)

That shouldn't prevent any client of Kubernetes from querying those CRDs stored as `v1` using either (`v1` or `v1beta1`) version:

```console
$ kubectl describe customresourcedefinitions.v1.apiextensions.k8s.io kongplugin
$ kubectl describe customresourcedefinitions.v1beta1.apiextensions.k8s.io kongplugin
```

Both work, and each returns the CRD converted to the API version requested.

So, IIUC, the CRDs stored as v1 shouldn't prevent us from making the lookup check request v1beta1.

**Comment by rainest** [comment]
It will for now, but that should break when 1.22 removes v1beta1, correct?

https://github.com/Kong/charts/pull/323 is more complex, but should future-proof for that. @navaati that change works on my 1.15 test instance, can you check out that branch locally to confirm on your cluster as well?

**Comment by navaati** [comment]
Ok, gonna test, maybe only on Monday though :/.

Agree that this will break when v1beta1 is removed. So either at that time you bump the version requirement for the chart, or you do some trickery with Helm using conditionals with the `.Capabilities` object.

**Comment by navaati** [comment]
Hi. Bit late, but for one additional data point I can confirm that this version worked just fine on my 1.15 clusters. Thanks for the good work guys, and cheers to your 2.0.0 release !
