### ISSUE TITLE
feature request: dashboard provisioning via chart

### ISSUE THREAD

**Issue by naseemkullah** [Kong/charts#328]
Hello,

It would be convenient to be able to provision a configmap containing https://grafana.com/grafana/dashboards/7424 as done in fluent-bit chart [here](https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/templates/configmap-dashboards.yaml).

The caveat is that the dashboard configmap in this chart and the dashboard hosted on grafana.com will be decoupled and have to stay in sync manually afaik when updates occur (or they can drift 🤷 ).

Does that sound good? If so I can open a PR.

**Comment by shaneutt** [comment]
As an opt-in yes, this would be welcome thank you! Please feel free to submit a PR :bow:
