### ISSUE TITLE
Allow mounting volumes

### ISSUE THREAD

**Issue by anderskswanson** [Kong/charts#330]
Hi, 

Would it be useful to allow mounting of volumes on Kong? This can be useful for sharing files/logging that aren't appropriate for ConfigMaps or Secrets. Looking at the Chart configuration it doesn't appear to currently be possible to mount an arbitrary volume onto Kong.

**Comment by ttony** [comment]
Hi @anderskswanson , you can check on #317  as there is option for you to create userDefinedVolume and userDefinedVolumeMount.

**Comment by anderskswanson** [comment]
#317
