### ISSUE TITLE
Kong cannot connect to Azure Postgres - Flexible Server type

### ISSUE THREAD

**Issue by ctrongminh** [Kong/charts#331]
Hi All,

I'm installing Kong using the below command

```
helm install kong/kong \
  --name-template kong \
  --set proxy.loadBalancerIP=x.x.x.x \
  --set proxy.ingress.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="kong" \
  -f values.yaml 
```

The values.yaml is
```
replicaCount: 2

namespace: "kong"

env:
  database: "postgres"
  pg_host : "postgres-url" 
  pg_port : "5432"
  pg_timeout : "5000"
  pg_user : "kong"
  pg_password : "kong"
  pg_database : "kong"
 
 
postgresql:
  enabled: false
 
ingressController:
  installCRDs: false
 
admin:
  enabled: true
  http:
    enabled: true
  type: "ClusterIP"
 
proxy:
  enabled: true
  type: LoadBalancer
```

After running the install command, I check the pod and see that the "kong-init-migrations" pod status is ERROR and then CrashLoopBackOff.

I then create a separate k8s job with the same yaml file as "kong-init-migration" job, and input --vv (I got the yaml by running the helm install with --dry-run flag)

`command: [ "/bin/sh", "-c", "kong migrations bootstrap --vv" ]`

And this is the output of the "kubectl logs kong-init-migration-xxx"

```
2021/04/06 02:32:23 [verbose] preparing nginx prefix directory at /kong_prefix
2021/04/06 02:32:23 [verbose] SSL enabled on 
2021/04/06 02:32:23 [verbose] proxy SSL certificate found at /kong_prefix/ssl/kong-default.crt
2021/04/06 02:32:23 [verbose] proxy SSL certificate found at /kong_prefix/ssl/kong-default-ecdsa.crt
2021/04/06 02:32:23 [verbose] SSL enabled on 
Error: 
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:102: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: FATAL: no pg_hba.conf entry for host "x.x.x.x", user "kong", database "kong", SSL off
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:102: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:48: in function <init_worker_by_lua:46>
        [C]: in function 'xpcall'
        init_worker_by_lua:55: in function <init_worker_by_lua:53>
2021/04/06 02:32:23 [verbose] admin SSL certificate found at /kong_prefix/ssl/admin-kong-default.crt
2021/04/06 02:32:23 [verbose] admin SSL certificate found at /kong_prefix/ssl/admin-kong-default-ecdsa.crt
2021/04/06 02:32:23 [debug] searching for OpenResty 'nginx' executable
2021/04/06 02:32:23 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.17.8.2'
2021/04/06 02:32:23 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2021/04/06 02:32:23 [debug] testing nginx configuration: KONG_NGINX_CONF_CHECK=true /usr/local/openresty/nginx/sbin/nginx -t -p /kong_prefix -c nginx.conf
```

However, If I create an Azure Postgres with Single Server, I can successfully install Kong with the same command and values.yaml as above. (Note: we need to update the pg_host for new server, and add pg_ssl: "on", if we force ssl).

I'm not sure if I need to configure anything else for the Azure Postgres flexible server type to work with Kong, but at least it works with the Single Server type.

I post this here to see if anyone has the same problem with Azure PostGres Flexible server type as it costs me some time to debug.

**Comment by guidowalter** [comment]
Same issue here...

**Comment by rainest** [comment]
Combing through some old issues and saw that this hadn't attracted any attention. I hadn't tried to answer it initially because I don't have much experience with Azure's Postgres, but have since found someone else mentioning the same: https://gist.github.com/bgarcial/16de91dd49f2f0ab60558015cb9bb245 indicates you can have it add the appropriate pg_hba entries with:

```
az postgres server firewall-rule create -g postgres-rg -s k8s-postgresql1 -n allow --start-ip-address 51.138.54.63 --end-ip-address 51.138.54.63
```
You'd need to adjust the addresses for your local environment. Does that clear the issue?
