### ISSUE TITLE
any plan to expose init container in helm chart?

### ISSUE THREAD

**Issue by lumincui** [Kong/charts#334]
I want to run `luarocks` command to install dependencies for my own custom plugin but don't have to modify the image itself.
One way is combine dependencies into configmap and mount into pod with custom plugin codes. There are some limits on this plan. First, configmap can't be more than 1M due to kubernetes object limit. Second, when your plugin depends on many plugin, it's hard to maintain file paths.
Another way is run init container before kong bootstrap, but there is no support in kong helm chart.
So, is there any plan to expose init container config in values file of helm chart?

**Comment by ttony** [comment]
you can check on #317 . it has been merged.
