### ISSUE TITLE
Outage: Bintray end of activity migration 

### ISSUE THREAD

**Issue by fvillain** [Kong/charts#337]
Hello,

We are currently in the middle of [bintray's brown-out session](https://status.bintray.com/) and kong deployments from the helm-chart is failling because it's unable to pull: `kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller` 

Is there any plan to move out from bintray , as it will end activity on May, 1st, 2021 ?
Do we have already some other registry available to download those images ?

Related issues: https://github.com/Kong/kong/issues/7024

**Comment by hbagdi** [comment]
We are migrating away from Bintray and to Dockerhub: https://hub.docker.com/r/kong/kubernetes-ingress-controller.
Please use Docker hub. It has old versions and we will upload new versions in there going forward.
Apologies for the inconvenience here.

**Comment by mflendrich** [comment]
> Please use Docker hub

In other words, in the chart's values, please set `ingressController.image.repository` to `kong/kubernetes-ingress-controller`.

We're cutting a patch release of the Helm chart in https://github.com/Kong/charts/pull/338 that will make it the default.

**Comment by mflendrich** [comment]
Chart 1.15.2, with the new default ingress controller location, is out.

Release for 2.0.0-rc.3 with the same fix is in progress: https://github.com/Kong/charts/pull/339
