### ISSUE TITLE
Skip plugin check, in the CRD template

### ISSUE THREAD

**Issue by miguelrivera** [Kong/charts#346]
Would it be possible to replace the:
`{{- else -}}` [on custom-resource-definitions.yaml line: 13](https://github.com/Kong/charts/blob/e4089d52671814d75c1e8eeaefb7aaef8510df41/charts/kong/templates/custom-resource-definitions.yaml#L13)
with:
`{{- else if (not .Values.ingressController.skipPluginCompabilityCheck) -}}` ? 

It would make life a little easier when running in a pretty locked down environment
@rainest @hbagdi

**Comment by rainest** [comment]
What restrictions exist in your environment, and how does Helm actually fail?
