### ISSUE TITLE
Kong Enterprise Gateway migration from Bintray

### ISSUE THREAD

**Issue by lena-larionova** [Kong/charts#353]
Charts and sample config files are referencing the bintray location for the Enterprise gateway image:

https://github.com/Kong/charts/blob/e4089d52671814d75c1e8eeaefb7aaef8510df41/charts/kong/values.yaml#L62

The new location is `kong/kong-gateway`. Could we get all relevant files updated with this info? 
https://hub.docker.com/r/kong/kong-gateway/tags?page=1&ordering=last_updated

This also applies to content in the kong/kubernetes-ingress-controller repo (eg [this manifest](https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/main/deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml), which is what the docs use) - I can also open a separate issue there, if that would be preferable.

**Comment by rainest** [comment]
Changed in https://github.com/Kong/charts/pull/349 and pending release: https://github.com/Kong/charts/pull/351
