### ISSUE TITLE
Manual assign cluster IP to admin enable.

### ISSUE THREAD

**Issue by pragasitcha** [Kong/charts#39]
Hi Kong's team 
Please help me about this issue.

After use helm install Kong on kubernetes  i ve tried to manual assign cluster ip to admin.

my config below.

helm install mykong kong/kong \
--set proxy.type=ClusterIP,proxy.clusterIP=10.96.10.1 \
--set admin.enabled=true,admin.type=ClusterIP,admin.clusterIP=10.96.10.2 \

proxy.type=ClusterIP,proxy.clusterIP=10.96.10.1 >> This work like a charm. IP 10.96.10.1 assign to kong proxy without problem.

problem start here ,In an admin config  there s no options for setting  admin.clusterIP in documents, 
Ive tried admin.clusterIP=10.96.10.2 as above but theres no luck.

Is there another way to set admin.clusterIP or i might missing something ? 

Thank you in advance

**Comment by hbagdi** [comment]
There is none. PR welcome.

**Comment by pragasitcha** [comment]
OK Thank you.
