### ISSUE TITLE
Can Hybrid mode disable ingressController on data-plane?

### ISSUE THREAD

**Issue by gung-rgb** [Kong/charts#398]
from my understanding, kong dat plane fetch data from cluster communication by /v1/outlet, so ingressController can be disable in ingressController?

**Comment by rainest** [comment]
If I understand your question correctly, yes, if you use hybrid mode along with the ingress controller, you will disable the ingress controller on your data plane instances, and enable it on control plane instances.

The controller will configure control planes from Ingresses, and the control planes will then ship that configuration to data planes.

Will go ahead and close this out, but if I misunderstood your question or you had a follow up, please respond back and we'll reopen it.
