### ISSUE TITLE
Kong Enterprise 2.4.x license support

### ISSUE THREAD

**Issue by ludovic-pourrat** [Kong/charts#412]
Hi according to https://docs.konghq.com/enterprise/2.4.x/deployment/licenses/deploy-license/ the Kong enterprise license is not anymore fetch from the KONG_LICENSE_DATA, but must be placed in /etc/kong/license.json.

Btw, there is no simple way to mount that file int /etc/kong that already exists, appart from copying it from another mount location.

Should the license provided via the API then ?

**Comment by rainest** [comment]
Are you actually seeing 2.4 fail to load a license from KONG_LICENSE_DATA? The code to read it from there still appears to be unchanged, and I'm able to start a 2.4 test instance using KONG_LICENSE_DATA still. I think that was just an omission in the updated documentation--if you can confirm it works for you also, I'll ask the docs team to correct that and indicate that the environment variable is still supported.

**Comment by ludovic-pourrat** [comment]
Yes I do confirm it works still with the KONG_LICENSE_DATA, and I was getting confused by the documentation, that dropped that part.

Thanks for your response.
