### ISSUE TITLE
refactor helm test scripts into reusable functions

### ISSUE THREAD

**Issue by shaneutt** [Kong/charts#416]
For KIC 2.0 we created a new `scripts/` dir where we added several helm tests. These tests have some repeating functionality that could be sourced out into functions used between scripts as a minor refactor.

Also CI does all tests in one long serial workflow: we should make these more parallel

Acceptance Criteria:
- [ ] common functionality in `scripts/` moved into source-able functions
- [ ] CI workflows for integration tests broken out into concurrent steps

**Comment by mflendrich** [comment]
won't fix per se - @shaneutt suggested that what makes more sense as a starting point is writing new tests, and performing such refactors on a reactive basis.
