### ISSUE TITLE
Deployed Kong ingress controller but unable to disable port 80 on NLB 

### ISSUE THREAD

**Issue by jayeshnazre** [Kong/charts#434]
I used the helm chart and am able to create a NLB in front of the Kong proxy successfully. However the Auto generated NLB via the proxy (Loadbalancer type)  exposes both port 80 as well as 443 (one targetgroup per port). I am successfully terminating my SSL at NLB using AWS ACM. 
The issue I am having is that I can get to my services inside my EKS (Kubernetes) cluster via http as well as https as both Target groups are exposed via the default settings in values.yaml. I tried to disable the http section by doing the below changes in values.yaml file
proxy:
   http:
      **enabled: false**
      servicePort: 8000
      containerPort: 8000

This removes the exposure of port 80, however I am unable to access any services inside my EKS cluster once that is done. 
It seems like my NLB needs port 80 to connect to my backend services
Any idea what I am doing wrong here?

**Comment by rainest** [comment]
You likely need several of the community-provided annotations suggested at https://github.com/Kong/charts/blob/498f7eaeb6bb604778d5d3ea23030484e2ed3a2a/charts/kong/values.yaml#L209-L213

Specifically, if you want the connection to continue to Kong over TLS, I believe you'll want https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#backend-protocol set to `tls` and 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#ssl-ports set to `kong-proxy-tls`.
