### ISSUE TITLE
KIC 2.0 Support

### ISSUE THREAD

**Issue by shaneutt** [Kong/charts#436]
We need to make KIC 2.0 the default image for the chart once it's released.

Acceptance Criteria:
- [x] ~KIC 2.x images are now the chart default~ https://github.com/Kong/charts/pull/470
- [x] ~multiple namespaces watching support is available in the chart values~ https://github.com/Kong/charts/pull/420

**Comment by shaneutt** [comment]
blocked until 2.0 release on [KIC](https://github.com/kong/kubernetes-ingress-controller) occurs.

**Comment by hhoover** [comment]
Unblocked? https://github.com/Kong/charts/blob/f81b0dc215ae9a939cef72becd9bda3a9cd307e0/charts/kong/values.yaml#L400

**Comment by shaneutt** [comment]
> Unblocked?
> 
> https://github.com/Kong/charts/blob/f81b0dc215ae9a939cef72becd9bda3a9cd307e0/charts/kong/values.yaml#L400

Yes, we're all set now as of https://github.com/Kong/charts/pull/470 (but was not linked so didn't autoclose). All set :+1:
