### ISSUE TITLE
Chart upgrade needs to spin down controller during v1 to v2 upgrade when using DB mode

### ISSUE THREAD

**Issue by shaneutt** [Kong/charts#450]
During the upgrade from `v1` to `v2` when DB mode is enabled (e.g. `postgres`) we shouldn't use a standard rollout upgrade.

We shouldn't allow any period of time where both controllers are acting on the proxy at the same time to avoid:

- 1.x and 2.x "fighting" over the data-plane configuration
- 2.x ending up writing a new parallel batch of config unrelated to 1.x's config
- other untested scenarios where both control-planes are actively trying to manage the data-plane.

**NOTE**: this doesn't affect DBLESS where the proxy pod will be completely recreated (and will be separate) anyhow.

Acceptance Criteria:
- [ ] when upgrading from v1 to v2 with DB mode backend the old controller is terminated _before_ the new controller is spun up

**Comment by mflendrich** [comment]
This seems to implicitly assume that KIC runs in the same pod as proxy if and only they run in dbless mode. Which is not an assumption we can make.

I think that we have the following constraints:
- guarantee no proxy downtime during upgrade
- guarantee no "fight" over admin api between v1 and v2 which leverage unrelated leader election mechanisms

**Comment by rainest** [comment]
Simplest solution here is that you just run an initial `helm upgrade` that does not change the version, but sets the controller off. For the subsequent `helm upgrade`, you bump the controller version and re-enable the controller.

This makes a brief window when nothing is updating configuration.

This should be part of the chart UPGRADE.md instructions.

**Comment by shaneutt** [comment]
> Simplest solution here is that you just run an initial `helm upgrade` that does not change the version, but sets the controller off. For the subsequent `helm upgrade`, you bump the controller version and re-enable the controller.
> 
> This makes a brief window when nothing is updating configuration.
> 
> This should be part of the chart UPGRADE.md instructions.

I'm definitely in favor of this change as the default case.

I would also be in favor of a `pre-upgrade` [hook](https://helm.sh/docs/topics/charts_hooks/) that 0 scales the controller pods and waits for termination prior to the upgrade if it detects db mode enabled.
