### ISSUE TITLE
Add support for running Kong in Debug mode ?

### ISSUE THREAD

**Issue by codeaprendiz** [Kong/charts#457]
Hi amazing folks,

How can I run kong in debug mode so that i can actually see the headers coming in a HTTP requst. Other ingress controller provide this support. 
I didn't find any thing related to logging level in values.yaml file.

**Comment by rainest** [comment]
We handle header logging via [logging plugins](https://docs.konghq.com/hub/#logging). If you're using the controller, you'll create a [KongPlugin](https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/references/custom-resources/#kongplugin) instance for one of those plugins and [attach them to an Ingress or Service](https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/guides/configure-acl-plugin/) (the second guide is for other plugins, but the general principle is the same).

Other (not header) debug functionality is available by setting `env.log_level=debug` (for logging diagnostic information about Kong internal processes to stderr) or by sending a `Kong-Debug: 1` header with your request (to include route and service matching information in response headers).

I'll go ahead and close this, but if you have additional questions, respond back to let us know and we'll reopen the issue.
