### ISSUE TITLE
Enable go plugins via chart?

### ISSUE THREAD

**Issue by kjico** [Kong/charts#46]
I wonder if it's supported to enable go plugin support via the chart somehow?
Thanks

**Comment by hbagdi** [comment]
Yes, you need to build a Docker image with the plugins binary installed in the image itself.

The configuration for Go plugins can be added via `env` section as well. There is nothing more to be done in the Helm chart to add support for Go plugins.

Please re-open if I'm wrong.

**Comment by hbagdi** [comment]
Yes, you need to build a Docker image with the plugins binary installed in the image itself.

The configuration for Go plugins can be added via `env` section as well. There is nothing more to be done in the Helm chart to add support for Go plugins.

Please re-open if I'm wrong.
