### ISSUE TITLE
Ingress resource for a Kong service uses old extensions/v1beta1 API

### ISSUE THREAD

**Issue by cpu601** [Kong/charts#461]
When creating Ingress objects for Kong services like Kong Manager or Portal etc. the Helm chart uses an old API version to create those Ingress objects, which is not available anymore starting Kubernetes v1.22.

Hence, Helm deployments using those Ingress objects will fail on newer Kubernetes installations:

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1"`

*API removals for Kubernetes v1.22*
https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes

*Old API being used in Helm chart:*
https://github.com/Kong/charts/blob/b87a69dcb92928e228aad59608b439f02ad65f6e/charts/kong/templates/_helpers.tpl#L69

**Comment by rainest** [comment]
This is resolved in the 2.4.0 release: https://github.com/Kong/charts/commit/1308ba39b7aa5be5f9022871b7a84b2deacfe3bb

If you're seeing issues still with the new functionality, please open a new issue to let us know what isn't working.
