### ISSUE TITLE
Support for Ingress controller kubernetes  v1.22.2

### ISSUE THREAD

**Issue by varunsais** [Kong/charts#472]
Error: INSTALLATION FAILED: failed to install CRD crds/custom-resource-definitions.yaml: CustomResourceDefinition.apiextensions.k8s.io "kongconsumers.configuration.konghq.com" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked as storage version, status.storedVersions: Invalid value: []string(nil): must have at least one stored version]

- The CRD Definition has to be updated to refer “versions” as mentioned in https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions. It is having as “version” only in specification.

- Ingress resource specification has to be updated as mentioned in to replace deprecated fields. https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

**Comment by rainest** [comment]
Which chart version are you using? The latest, 2.4.0, includes updated CRDs and Ingresses for 1.22 compatibility. You may need to run `helm repo update` if you haven't recently.

I'm able to install on 1.22 successfully:
[test_122.txt](https://github.com/Kong/charts/files/7333574/test_122.txt)

While our CRDs in the chart don't include storedVersion information, it looks like this is acceptable if there's only one version (as is the case for our CRDs): Kubernetes populates that automatically if it's not present.
