### ISSUE TITLE
No labels on CRD

### ISSUE THREAD

**Issue by alecerf** [Kong/charts#477]
Currently we're getting all the K8s objects using the labels.
But we've seen that the [Kong CRD](https://github.com/Kong/charts/blob/main/charts/kong/crds/custom-resource-definitions.yaml) don't have any labels in the metadata.

Is there a technical reason for that or do you plan to add them?

It would be nice to have like what you've done to other objects
`labels:
    {{- include "kong.metaLabels" . | nindent 4 }}`

**Comment by rainest** [comment]
It's not possible to template CRDs. For [a variety of reasons](https://github.com/helm/community/blob/main/hips/hip-0011.md), Helm basically just inspects the contents of the `crds` directory during `helm install`, sees if a CRD with the same name exists, and creates the CRD if not. That doesn't run CRDs through the templating engine at all and means that the CRD may have been created by any install of the chart.

It doesn't look like CRDs support any field selectors that would be useful here (it seems like it would make sense to support `spec.group`, but that doesn't work and it'd require upstream changes to Kubernetes itself to allow it), so absent an in-Kubernetes solution, this is your next-best option:

```
kubectl get crd | grep configuration.konghq.com
```
