### ISSUE TITLE
ServiceMonitor doesn't seem to work

### ISSUE THREAD

**Issue by naramiss** [Kong/charts#478]
Hi, I am facing an issue when I try to install KIC with the default ServiceMonitor. No ServiceMonitor is created, I tried to run `helm template mykong kong/kong --namespace kong --set serviceMonitor.enabled=true --set serviceMonitor.labels.release=promstack > values.yaml` but when I look at values.yaml, no ServiceMonitor is generated. I don't understand, could you help please ?

**Comment by rainest** [comment]
Do you have the Prometheus Operator installed? The ServiceMonitor CRD is something that provides: we can't (and don't) create one if it's not available, even if enabled: https://github.com/Kong/charts/blob/main/charts/kong/templates/servicemonitor.yaml#L1

**Comment by michbeck100** [comment]
@naramiss the ServiceMonitor depends on `monitoring.coreos.com/v1`. So you have to use `--api-versions  monitoring.coreos.com/v1` (see https://helm.sh/docs/helm/helm_template/)

**Comment by jmadureira** [comment]
Hello @michbeck100

I've stumbled upon the problem @naramiss raised and can confirm that when running

```sh
helm template kong ... --include-crds --values ... --set serviceMonitor.enabled=True --api-versions  monitoring.coreos.com/v1
```

The `ServiceMonitor` gets rendered as expected.
The problem is that this is for local testing. When running against a k8s cluster the `ServiceMonitor` isn't installed even though the target cluster has the operator running:

```sh
> kubectl get --raw /apis

{
  "kind": "APIGroupList",
  "apiVersion": "v1",
  "groups": [
   ...
    {
      "name": "monitoring.coreos.com",
      "versions": [
        {
          "groupVersion": "monitoring.coreos.com/v1",
          "version": "v1"
        },
        {
          "groupVersion": "monitoring.coreos.com/v1alpha1",
          "version": "v1alpha1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "monitoring.coreos.com/v1",
        "version": "v1"
      }
    }
  ]
}
```
