### ISSUE TITLE
NOTES.txt contains broken url

### ISSUE THREAD

**Issue by bf-akvanvig** [Kong/charts#487]
URL to getting started guide in NOTES.txt no longer works, should be replaced

https://github.com/Kong/charts/blob/main/charts/kong/templates/NOTES.txt#L12

I assume this is the new correct url?
https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/guides/getting-started/

**Comment by rainest** [comment]
Yes, thank you for letting us know. I've updated it and it will be fixed in the next release.
