### ISSUE TITLE
Add chart value option to disable the custom resource definitions

### ISSUE THREAD

**Issue by janvanzoggel** [Kong/charts#502]
Our Kong deployment topology on Red Hat Openshift (K8s) is based upon our platform team to deploy a version of the Kong Helm chart in a centralised namespace with ONLY the CRDs due to permissions / requirements on the kubernetes platform.

```yaml
kong:

  ingressController:
    enabled: false
    installCRDs: false

  deployment:
    kong:
      enabled: false
```

The Kong team wants to deploy the kong pod(s) in their own namespace (but don't have privileges to install some of the custom resources CDSs hence the solution above by the platform team) but:

https://github.com/Kong/charts/blob/main/charts/kong/templates/custom-resource-definitions.yaml

```yaml
{{- $installCRDs := false -}}
{{- if .Values.ingressController.installCRDs -}}
  {{- if .Values.ingressController.enabled -}}
    {{/* Managed CRD installation is enabled, and the controller is enabled.
    */}}
    {{- $installCRDs = true -}}
  {{- else if (not .Values.deployment.kong.enabled) -}}
    {{/* Managed CRD installation is enabled, and neither the controller nor Kong or enabled.
         This is a CRD-only release.
    */}}
    {{- $installCRDs = true -}}
  {{- end -}}
{{- else -}}
```

There is no option to facilitate the Helm deployment without the CRDs.

**Proposed solution:**
Allow an additional value like Values.installCRDs and add an If to check if this is not set to false.

**Comment by janvanzoggel** [comment]
additionally we want to deploy Kong multiple times on 1 K8S/Openshift cluster so assume that moving forward this would also cause problems with each Kong deployment doing a mandatory deployment of the CRDs

**Comment by Benjaminvdv** [comment]
Furthermore, when using helm v3, the CRDs are forcefully installed automatically. This is due to the fact that helm v3 automatically installs resources inside the `crds` folder.
Docs: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

**Comment by rainest** [comment]
Helm 3's `--skip-crds` option is the proper way to handle this now.

The template still exists to support releases installed prior to Helm 3. It's not used otherwise; you're seeing Helm 3's default behavior instead.

Will go ahead and close this, but let us know if you have additional questions.

**Comment by Benjaminvdv** [comment]
> Helm 3's `--skip-crds` option is the proper way to handle this now.
> 
> The template still exists to support releases installed prior to Helm 3. It's not used otherwise; you're seeing Helm 3's default behavior instead.


You are correct. Though, when using a GitOps tool such as ArgoCD, no such option is available. 

Thanks for your response though!

**Comment by rainest** [comment]
Yeah, looks like they have an open issue to expose it: https://github.com/argoproj/argo-cd/issues/6252

Installing CRDs using your cluster administrator beforehand will make this a non-issue though, since after Helm will just detect that they're already present and proceed.
