### ISSUE TITLE
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:437: error loading plugin schemas: on plugin 'kong-plugin-moesif': kong-plugin-moesif plugin is enabled but not installed

### ISSUE THREAD

**Issue by moconno** [Kong/charts#51]
Hi, 
I'm trying to deploy docker kong enterprise to my k8s cluster.  I want to include the kong-plugin-moesif plugin, but it is causing my kong deployment to fail with the error in the title.  Below are some files I've configured.  Am I missing something?  

# DockerFile:
FROM kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:1.3.0.1-alpine
USER root
RUN luarocks install --server=http://luarocks.org/manifests/moesif kong-plugin-moesif

# Values.yaml
env:
   plugins: bundled, kong-plugin-moesif

# configure-plugins.yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kong-plugin-moesif
  labels:
    global: "true"
disabled: false
config:
  application_id: {{ .Values.moesif.applicationId }}
plugin: kong-plugin-moesif

**Comment by hbagdi** [comment]
It should be:

`plugins: bundled, moesif`

and then use `plugin: moesif` in KongPlugin resource.

Please close this issue if your problem is resolved. Thanks.

**Comment by moconno** [comment]
Yes, that worked.  Thanks!
