### ISSUE TITLE
cluster conflicts with ArgoCD Helm deployments

### ISSUE THREAD

**Issue by bdecoste** [Kong/charts#514]
Need to rename the "cluster" element to something else to avoid the conflict. https://github.com/Kong/charts/blob/main/charts/kong/templates/service-kong-cluster.yaml

**Comment by rainest** [comment]
How does this conflict/do you have anything from the ArgoCD side we can reference?

**Comment by bdecoste** [comment]
Working on the Argo details and a PR ...

**Comment by rainest** [comment]
Are there alternatives we can consider (ideally telling Argo to not apply arbitrary restrictions on downstream values.yaml)? Changing config paths like that is annoying breaking change.

**Comment by bdecoste** [comment]
I am investigating the Argo details and any workarounds. Proposed PR would add an additional field (e.g. clusterservice) that duplicates the current cluster functionality to keep backwards compatibility

**Comment by rainest** [comment]
@bdecoste checking on this again, had you found any details?
