### ISSUE TITLE
[Chart] Kong Manager OSS not supported for this chart

### ISSUE THREAD

**Issue by kholisrag** [Kong/charts#517]
Hi, based on this image

![img1](https://docs.konghq.com/assets/images/docs/gateway/gateway_overview.png)
and [reference](https://docs.konghq.com/gateway/) 
its say that Kong Manager can be used for OSS,
but based on following line :
https://github.com/Kong/charts/blob/cb1d9388dee0ab58ea501934b66db003e2c2768d/charts/kong/templates/deployment.yaml#L201-L217

we need to have enterprise license
so this is a bug for the chart? or the [reference](https://docs.konghq.com/gateway/) say something wrong?

Thanks in advance!

**Comment by rainest** [comment]
It should work fine if you set `enterprise.enabled=true` despite not actually being Enterprise. Did you encounter some issue with that set? AFAIK the only change we needed to make was to remove the strict requirement to set a license, which we did a while ago.

That section of values.yaml predates the creation of the free mode kong-gateway image, when Enterprise was the only option for using Kong Manager. That's no longer the case, but changing the names of values.yaml fields breaks existing configurations, so we don't usually modify them unless we have to.

**Comment by trhumphries** [comment]
So Kong Manager is usable with OSS version by turning on enterprise.enabled=true however does this change any thing else in how the OSS version works?

**Comment by rainest** [comment]
Nope. It's only toggling parts of the chart templates on or off.

About all you'd want to do is explicitly disable the Portal Services:

https://github.com/Kong/charts/blob/main/charts/kong/values.yaml#L798
https://github.com/Kong/charts/blob/main/charts/kong/values.yaml#L842

They won't cause any harm if enabled, but aren't actually available.

Will go ahead and close this, but if you do encounter any issues using free mode, please respond back and we'll reopen it.

**Comment by trhumphries** [comment]
I started a new issue at https://discuss.konghq.com/t/kong-manager-via-helm/9531
