### ISSUE TITLE
CRD issue KongIngress v1: The option https_verify_certificate has been removed from configuration.konghq.com/v1

### ISSUE THREAD

**Issue by HansK-p** [Kong/charts#535]
It looks like the parameter https_verify_certificate and quite a few other parameters were removed from the configuration.konghq.com/v1 KongIngress CRD in commit 63901a05e67f1eb3b846d691e84a81027a4f473b on  Wed Sep 8 15:29:13 2021 -0400.

As a result, it is no longer possible to turn of SSL certificate checking against a upstream service when using CRDs from the official Kong Helm chart, version 2.6.4.

The base CRD for the default kubernetes-ingress-controller docker image pulled by a deployment based on the official Kong Helm chart can be found as  https://github.com/Kong/kubernetes-ingress-controller/blob/v2.1.1/config/crd/bases/configuration.konghq.com_kongingresses.yaml. This base crd has support for the option https_verify_certificate.

I have re-added the option to our deployed CRD by using the following Kustomize transformation:
<pre>
patches:
- target:
    kind: CustomResourceDefinition
    name: kongingresses.configuration.konghq.com
  patch: |-
    - op: add
      path: /spec/versions/0/schema/openAPIV3Schema/properties/upstream/properties/healthchecks/properties/active/properties/https_verify_certificate
      value:
        type: boolean
</pre>
and validated that this is a working workaround.

I believe this change to the CRD breaks the design and contract around Kubernetes CRD APIs and stability. Ref. https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md.

**Comment by rainest** [comment]
Not entirely sure how it got stripped out, but we needed to update the CRDs anyway. The current version is generated directly from the underlying types, whereas the old version was hand-written and were difficult to review for correctness. That update is staged in 2.7.0.

**Comment by HansK-p** [comment]
Then I understand why this happened, and I'm fully in support of going from something that's hand written to something that's automatic. I suppose you should still look at how it could happen as the issue must have hit wider than just our deployment where such "basic" issues after an upgrade gave us quite a surprise. It is in non-prod and doing a rollback worked well, so no crises for us.
