### ISSUE TITLE
Tests fail if http is disabled for the proxy

### ISSUE THREAD

**Issue by ghost** [Kong/charts#545]
The tests have http:// hardcoded and will fail if `proxy.http.enabled = false`.  If this is disabled it should use https:// instead.  It also seems strange to have the restartPolicy set to OnFailure for a test.  If the test fails, like in the case of http being disabled, it will just keep running the tests in a crashloop.

**Comment by rainest** [comment]
How are you using the tests in practice? We'd originally put them in place for our CI tooling and didn't expect that end users would run them, so they make some configuration assumptions based on the default configuration we test with.

As they're templates also, you should be able to use conditionals based on the `proxy.<http/tls>.enabled` similar to [what we have for determining the admin API URL](https://github.com/Kong/charts/blob/fd4cf30c8042a7c4a029df31790a9998f5d69308/charts/kong/templates/_helpers.tpl#L305-L313). Would you be interested in contributing a PR?

**Comment by ghost** [comment]
Our pipelines run helm test and rollback if the tests don't pass.  I will see if I can get some cycles to put a PR together.  It should be pretty straight forward.

**Comment by ghost** [comment]
Hoping to get some time freed up to take a look at this
