### ISSUE TITLE
Not using Kong&postgres docker images, what should be changed in the values.yml file

### ISSUE THREAD

**Issue by ngingihy** [Kong/charts#548]
Hi, so i'm using harbor registry and have all the images in it. I'm just confused on where should I put the image name and harbor url in `values.yaml`

**Comment by rainest** [comment]
Kong/KIC images can be set via:
https://github.com/Kong/charts/blob/fd4cf30c8042a7c4a029df31790a9998f5d69308/charts/kong/values.yaml#L101-L103
https://github.com/Kong/charts/blob/fd4cf30c8042a7c4a029df31790a9998f5d69308/charts/kong/values.yaml#L425-L427

The Postgres subchart can be set under the `postgresql` section, using
https://github.com/bitnami/charts/blob/590c6b0f4e07161614453b12efe71f22e0c00a46/bitnami/postgresql/values.yaml#L15-L18

**Comment by ngingihy** [comment]
@rainest yes here is the image repo, where should i add harbor.com? it's the global registry i'm pulling all my images from

**Comment by rainest** [comment]
In the repository field. You'll have something like `harbor.com/user/postgres`

`kong/kubernetes-ingress-controller` is shorthand for `docker.io/kong/kubernetes-ingress-controller`. Including the repo domain is the standard format; the docker.io repo allows omitting its domain because the Docker client assumes it's the default.

**Comment by ngingihy** [comment]
and where to put secret?

**Comment by rainest** [comment]
The image sections include a `pullSecrets` section:

https://github.com/Kong/charts/blob/main/charts/kong/values.yaml#L114-L115 and https://github.com/bitnami/charts/blob/590c6b0f4e07161614453b12efe71f22e0c00a46/bitnami/postgresql/values.yaml#L28-L29
