### ISSUE TITLE
customEnv is ignored for ingress-controller Pod

### ISSUE THREAD

**Issue by edmund-wagner** [Kong/charts#562]
Using these helm values to set the timezone for kong pods:
 ```
 customEnv:
    TZ: "Europe/Berlin"
 ```
Unfortunatelly this is applyed by kong proxy and the init container pods but disregarded by the ingress-controller pod.

_helpers.tpl:382
`
{{- $completeEnv := mergeOverwrite $autoEnv $userEnv -}}
`
should probably be like this:
`
{{- $completeEnv := mergeOverwrite $autoEnv $userEnv  $customEnv -}}
`

**Comment by rainest** [comment]
Indeed. Would you be interested in submitting a PR to add it? It should source from a separate `.ingressController.customEnv` key since it's not necessarily the same set of variables provided to the Kong containers. You'd also need to populate it before adding `$userEnv` to the merge:

```
{{/*     
    ====== CUSTOM ENVIRONMENT VARIABLES ======     
*/}}  

{{- $customEnv := dict -}}        
{{- range $key, $val := .Values.ingressController.customEnv }}     
  {{- $upper := upper $key -}}     
  {{- $var := printf "%s" $upper -}}      
  {{- $_ := set $customEnv $var $val -}}     
{{- end -}}
```
