### ISSUE TITLE
Using github as helm remote does not get the latest version

### ISSUE THREAD

**Issue by fellipecmwbc** [Kong/charts#567]
Hi all, I am trying to use this repository in JFrog Artifactory as private a remote registry using [the releases url](https://github.com/Kong/charts/releases). As off today the latest version published here is **2.7.0**, however it is only pulling up to **2.6.4**. The only difference I have noticed is that the release **2.7.0** does not have a verified commit, but I am sure if this causing the issue. Can anyone please shed a light on this if possible? Note that I am using other git repo the same way and it picks up the latest.
Thanks in advance!

**Comment by rainest** [comment]
This is probably more a question for JFrog. Have you checked with them to confirm the cause? We don't have any insight into the functionality of Artifactory, but if there's some known requirement they have we can try to address it.

**Comment by fellipecmwbc** [comment]
Thanks @rainest, I will open a ticket with the vendor and come back if anything can be done.
