### ISSUE TITLE
Hybrid Mode - Certificate on control-plane 

### ISSUE THREAD

**Issue by danfukuoka** [Kong/charts#581]
Is it possible add certificate and sni to make control-plane services (manager, admin…) requests https? I could do that for the data-plane (proxy), but the https is not working for the other services on control-plane. I’m deploying Kong Enterprise Api Gatway (without Kong Ingress Controller) using Kong Helm.

Thanks

**Comment by rainest** [comment]
Are you looking to set up the certificates that Kong uses when you reach those services directly? You can do so by setting the various `_ssl_cert` and `_ssl_key` settings ([e.g. for the admin API](https://github.com/Kong/kong/blob/0973036503941c52c56f8a1be74b686a62a40cdd/kong.conf.default#L650-L658)) under `env` along with a [Secret mount](
https://github.com/Kong/charts/blob/b3e6644a27824d5b177caf515aabc7f2e96c7777/charts/kong/values.yaml#L373-L381).

SNIs are only used for proxy configuration (the kong.conf settings will just serve the cert provided regardless of whether the request SNI matches or not). If you were looking to instead configure those for access via the proxy without an ingress controller, you'd add the route/service/certificate/SNI same as any other, using the [service hostname](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) for the service's `host`.
