### ISSUE TITLE
Installation fails with default release manifest

### ISSUE THREAD

**Issue by snehil2** [Kong/charts#593]
**helm install kong/kong  --generate-name**

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Service.spec.ports[0]): unknown field "appProtocol" in io.k8s.api.core.v1.ServicePort, ValidationError(Service.spec.ports[1]): unknown field "appProtocol" in io.k8s.api.core.v1.ServicePort]

I am not using any values file and installing kong with default configs.

Helm version: 3.9.0-rc.1
Kubectl: Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"windows/amd64"}

**Comment by rainest** [comment]
Which Kubernetes version are you on? We added these since they're [useful for Istio users](https://github.com/Kong/charts/commit/fd4cf30c8042a7c4a029df31790a9998f5d69308) and should be available on modern versions. The ServiceAppProtocol was enabled by default as of 1.19: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

As 1.18 is EOL, we're unlikely to add functionality to omit those fields, especially since I don't think we can detect their availability automatically and they'd require a user-facing config option (Helm has tools to detect the availability of API versions, but not, as far as I know, whether feature flags are enabled).

**Comment by AnthonyKeydel** [comment]
Just encountered the same issue on our RKE cluster running k8s v1.17.2
Different cluster running 1.20.4 worked fine, although "the following commands:" after installing did not (nothing in .status.loadBalancer)

**Comment by DavidConnack** [comment]
Im also having issues with the default helm install:

ingress-controller logs:
`time="2022-05-15T11:42:58Z" level=info msg="Starting workers" logger=controllers.KongClusterPlugin.controller.KongV1KongClusterPlugin worker count=1
time="2022-05-15T11:42:58Z" level=error msg=namespace NetV1Ingress="{\"Namespace\":\"default\",\"Name\":\"demo\"}" error="resource not yet configured in the data-plane" logger=controllers.Ingress.netv1
time="2022-05-15T11:42:58Z" level=error msg=namespace NetV1Ingress="{\"Namespace\":\"default\",\"Name\":\"demo\"}" error="resource not yet configured in the data-plane" logger=controllers.Ingress.netv1
time="2022-05-15T11:42:58Z" level=error msg=namespace NetV1Ingress="{\"Namespace\":\"default\",\"Name\":\"demo\"}" error="resource not yet configured in the data-plane" logger=controllers.Ingress.netv1
time="2022-05-15T11:42:58Z" level=error msg=namespace NetV1Ingress="{\"Namespace\":\"default\",\"Name\":\"demo\"}" error="resource not yet configured in the data-plane" logger=controllers.Ingress.netv1
time="2022-05-15T11:42:58Z" level=error msg=namespace NetV1Ingress="{\"Namespace\":\"default\",\"Name\":\"demo\"}" error="resource not yet configured in the data-plane" logger=controllers.Ingress.netv1
time="2022-05-15T11:42:58Z" level=error msg=namespace NetV1Ingress="{\"Namespace\":\"default\",\"Name\":\"demo\"}" error="resource not yet configured in the data-plane" logger=controllers.Ingress.netv1
time="2022-05-15T11:42:59Z" level=error msg=namespace NetV1Ingress="{\"Namespace\":\"default\",\"Name\":\"demo\"}" error="resource not yet configured in the data-plane" logger=controllers.Ingress.netv1
time="2022-05-15T11:43:00Z" level=error msg=namespace NetV1Ingress="{\"Namespace\":\"default\",\"Name\":\"demo\"}" error="resource not yet configured in the data-plane" logger=controllers.Ingress.netv1
time="2022-05-15T11:43:03Z" level=error msg=namespace NetV1Ingress="{\"Namespace\":\"default\",\"Name\":\"demo\"}" error="resource not yet configured in the data-plane" logger=controllers.Ingress.netv1
time="2022-05-15T11:43:06Z" level=info msg="successfully synced configuration to kong."
time="2022-05-15T11:43:09Z" level=error msg="checking config status failed: %!w(*kong.APIError=&{500 An unexpected error occurred})"
time="2022-05-15T11:43:12Z" level=error msg="checking config status failed: %!w(*kong.APIError=&{500 An unexpected error occurred})"
time="2022-05-15T11:43:15Z" level=error msg="checking config status failed: %!w(*kong.APIError=&{500 An unexpected error occurred})"
time="2022-05-15T11:43:18Z" level=error msg="checking config status failed: %!w(*kong.APIError=&{500 An unexpected error occurred})"
time="2022-05-15T11:43:21Z" level=error msg="checking config status failed: %!w(*kong.APIError=&{500 An unexpected error occurred})"
time="2022-05-15T11:43:24Z" level=error msg="checking config status failed: %!w(*kong.APIError=&{500 An unexpected error occurred})"
time="2022-05-15T11:43:27Z" level=error msg="checking config status failed: %!w(*kong.APIError=&{500 An unexpected error occurred})"
time="2022-05-15T11:43:28Z" level=error msg="failed to connect to reporting server: dial tcp 35.169.37.138:61833: i/o timeout"
`

**Comment by rainest** [comment]
@DavidConnack in general you should file a separate issue unless you have the same issue as described in the original post.

If you're seeing `level=info msg="successfully synced configuration to kong."` logs that usually indicates that your system is working successfully. The status error is benign, see https://github.com/Kong/kubernetes-ingress-controller/issues/2435

**Comment by Mohammen1977** [comment]
Hi
I am facing the same problem here
Any help please ?

$ helm -n micro-onos install onos-umbrella onosproject/onos-umbrella
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/mohammed/.kube/kind
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/mohammed/.kube/kind
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.securityContext): unknown field "seccompProfile" in io.k8s.api.core.v1.PodSecurityContext
