### ISSUE TITLE
ingressController.replicasCount documented but not implemented

### ISSUE THREAD

**Issue by yspotts** [Kong/charts#6]
The documentation notes that one can specify the the number of replicas for the ingressController. However, this value is not actually available for configuration. As a result, I would assume the ingressController always defaults to 1 instance. Would be nice to be able to configure the number of replicas for the ingressController.

**Comment by hbagdi** [comment]
Ingress Controller runs in the same pod as Kong, the proxy.
You can control the number of replicas using the `replicaCount` variable.
The docs are out of date it seems.
