### ISSUE TITLE
Support OpenShift Route-Objects

### ISSUE THREAD

**Issue by wistefan** [Kong/charts#613]
For better integration of Kong deployments into OpenShift Environments, it would be good to have the option for using [Routes](https://docs.openshift.com/container-platform/4.10/rest_api/network_apis/route-route-openshift-io-v1.html) instead of the Ingress. 

If your ok with that, I can contribute a PR.

**Comment by rainest** [comment]
We do not intend to add support for OpenShift Routes. We are contributors to and are working on the CNCF's new [Gateway API standard](https://gateway-api.sigs.k8s.io/), which provides similar functionality (broadly, expressing proxy-level configuration in addition to the per-route configuration offered by Ingress).
