### ISSUE TITLE
Can't set customEnv property

### ISSUE THREAD

**Issue by mantasmatulis** [Kong/charts#618]
Hi,
I need to set the env variable for my custom Kong plugin and I use `customEnv` property to achieve that. Unfortunately, when I set any value to that key the customEnv variable doesn't appear. I set it in the values.yaml file but the variable doesn't exist when Kong starts. Any ideas or suggestions on what can be wrong?
e.g.
```yml
customEnv:
  TEST: "hello"
```

**Comment by pmalek** [comment]
Hi @DWMantas 

Do you mind sharing a bit more details? For instance what version of the chart are you trying to install?

I've just tried to install the most recent version `2.9.1` with the following `values.yaml`

```yaml
customEnv:
  client_name: testClient
```

and the env variable was added as expected to the deployment:

```console
$ k get deployments.apps -n kong3 kong-test1-kong -oyaml | grep CLIENT_NAME -C1
      - env:
        - name: CLIENT_NAME
          value: testClient
--
        env:
        - name: CLIENT_NAME
          value: testClient
```

**Comment by mantasmatulis** [comment]
The latest chart version solved the issue. Thanks!
