### ISSUE TITLE
terminationGracePeriodSeconds: field not declared in schema

### ISSUE THREAD

**Issue by flickers** [Kong/charts#639]
Hi Kong team,

I'm unable to deploy a Kong chart successfully after Helm Chart version 2.8.2 due to the following error:

> error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "terminationGracePeriodSeconds" in io.k8s.api.core.v1.Container

The above error is from Kong Helm chart v2.10.2
I've tried deploying on both kubernetes 1.21 and 1.22 both running in EKS
I'm using ArgoCD 2.4.4

I think the suspecting code is https://github.com/Kong/charts/blob/ab5d60f8342d91d2b9883d152c64be9cd7d3c174/charts/kong/templates/_helpers.tpl#L626
besides the fact the it says `.Values.ingressController.terminationGracePeriodSecond` and your values.yaml file has `ingressController.terminationGracePeriodSeconds` (Seconds plural)
I've tried both `terminationGracePeriodSeconds` and `terminationGracePeriodSecond` in my values file but that doesn't change the error. 

But after a lot of reading I think the reason is that terminationGracePeriodSeconds is not apart of the Kubernetes schema in spec.template.spec.containers. See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#pod-v1-core

**Comment by pmalek** [comment]
Hi @flickers 👋 

Thanks for your report! I believe #640 should fix your problem. We should have a release sometime this week which will have this fix.
