### ISSUE TITLE
Path Based rate limit still rate limiting other paths 

### ISSUE THREAD

**Issue by ronnie-webb2** [Kong/charts#641]
helm.sh/chart=kong-2.10.2 
kong/kubernetes-ingress-controller:2.3

**KongPlugin**

`apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-mobile
config:
  minute: 3
  limit_by: path
  path: /v3/services/register
  hour: 10000
  fault_tolerant: true
  hide_client_headers: false
plugin: rate-limiting`

**route ingress**

annotations:
    cert-manager.io/cluster-issuer: letsencrypt-integration
    external-dns.alpha.kubernetes.io/skip: 'true'
    konghq.com/plugins: rate-limiting-mobile
    kubernetes.io/ingress.class: kong-ingress-controller
status:
  loadBalancer:
    ingress:
      - ip: x.x.x.x
spec:
  rules:
    - host: example-host.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: example-host
                port:
                  number: 9142
    - host: example-host-1.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: example-host-1
                port:
                  number: 9142
    - host: example-host-2.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: example-host-2
                port:
                  number: 9142

Problem is I want to rate limit everything going to  /v3/services/register,  But every path gets rate limited. Any suggestions?

**Comment by PhilKuer** [comment]
This project is only for the Helm chart.

I think you should open this issue in the official Kong repository.

**Comment by rainest** [comment]
Duplicate of https://github.com/Kong/kubernetes-ingress-controller/issues/2669
