### ISSUE TITLE
CONTROLLER_ENABLE_CONTROLLER_INGRESS_CLASS_NETWORKINGV1 not disabled when KIC is Namespaced

### ISSUE THREAD

**Issue by jasiek-zywczak** [Kong/charts#648]
When running KIC in the namespaced mode we need to disable cluster scoped permissions. Unfortunately despite the fact documentation mention that watching ingressClass should be disabled in this situation, charts does not properly handle this. https://github.com/Kong/charts/tree/main/charts/kong#removing-cluster-scoped-permissions

https://github.com/Kong/charts/blob/e9c77a52a7ef4f90128ebff4d0fef6600fa6eda7/charts/kong/templates/_helpers.tpl#L372

**Comment by jasiek-zywczak** [comment]
there is a bug in KIC itself https://github.com/Kong/kubernetes-ingress-controller/issues/2712 even enabling this flag might not be enough :(

**Comment by rainest** [comment]
Closing since this is handled somewhere between https://github.com/Kong/kubernetes-ingress-controller/pull/2724 and https://github.com/Kong/charts/pull/611
