### ISSUE TITLE
No diagnostic port defined in charts (port 10256)

### ISSUE THREAD

**Issue by edorid** [Kong/charts#669]
After chart version 2.3.0, there is new diagnostic mode which not being enabled on deployment manifest.

Is it by design ?

**Comment by rainest** [comment]
The https://docs.konghq.com/kubernetes-ingress-controller/2.7.x/troubleshooting/#dumping-generated-kong-configuration server? Yes, it's not normally exposed; we don't expect it to be in consistent use and port-forwarding is the normal way to access it.

Will go ahead and close this but if you have any additional questions let us know.
