### ISSUE TITLE
Feature request: services CRD

### ISSUE THREAD

**Issue by mikemowgli** [Kong/charts#68]
Hi,
We like very much that the chart supports CRDs, and are looking forward for a Service CRD. Thanks to such a CRD, a backend application pipeline could change Kong's configuration so the gateway would point to the new backend application version. It would facilitate a lot dependency management between apps and the gateway. Is such a feature already considered?
Thank you

**Comment by hbagdi** [comment]
I'm not sure I understand you, could you give an example?

Currently, a Kubernetes Service corresponds to one or more services in Kong.

**Comment by hbagdi** [comment]
Closing due to lack of response. Please re-open if needed.
