### ISSUE TITLE
`udpProxy` uses `TCP` ports by default

### ISSUE THREAD

**Issue by jrsmroz** [Kong/charts#681]
## Problem

```console
helm install my-kong kong/kong -n kong --dry-run --set udpProxy.enabled=true --set 'udpProxy.stream[0].containerPort=9999' --set 'udpProxy.stream[0].servicePort=9999' | grep udp-proxy -A 20
# Source: kong/templates/service-kong-udp-proxy.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-kong-kong-udp-proxy
  namespace: kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-2.13.1
    app.kubernetes.io/instance: "my-kong"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "3.0"
spec:
  type: LoadBalancer
  ports:
  - name: stream-9999
    port: 9999
    targetPort: 9999
    protocol: TCP
  selector:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: "my-kong"
---
# Source: kong/templates/deployment.yaml
```

Without `UDP` parameter specified it defaults to `TCP`, even though we're clearly configuring an `udpProxy`

## Expected behaviour

When configuring `udpProxy`, the `UDP` should be default protocol.

**Comment by jrsmroz** [comment]
It works if `stream[].protocol` is explicitly set to `UDP`. Example have that included, but there is no explanation anywhere that it's required.

```yaml
udpProxy:
  enabled: true
  stream: 
    - containerPort: 9999
      servicePort: 9999
      protocol: UDP
```

**Comment by randmonkey** [comment]
> It works if `stream[].protocol` is explicitly set to `UDP`. Example have that included, but there is no explanation anywhere that it's required.
> 
> ```yaml
> udpProxy:
>   enabled: true
>   stream: 
>     - containerPort: 9999
>       servicePort: 9999
>       protocol: UDP
> ```

I think the problem is here: https://github.com/Kong/charts/blob/8af0b0391ff509942aa329f663530a0780f7e0d3/charts/kong/templates/_helpers.tpl#L277
The function sets default protocol to TCP when generating service port configurations of proxy service.
