### ISSUE TITLE
Declaring Kong CRDs in new Helm 3 crds directory

### ISSUE THREAD

**Issue by yspotts** [Kong/charts#7]
Helm introduced the ability to declare CRDs in a new `crds` directory (https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/). This solves an issue of using Kong as a dependency (subchart) of an umbrella chart and using the CRD (for example KongPlugin). This is currently not possible (or at the very least very challenging) in Helm 2 charts; see here: (https://github.com/helm/helm/issues/2994). 

Implementing helm 3 `crds` would be a nice feature enhancement.

**Comment by hbagdi** [comment]
Helm 3 compatibility has been on our radar but not a priority at the moment for us.
If you can send a PR that is backwards compatible with Helm v2, we will gladly accept the change!

**Comment by yspotts** [comment]
@hbagdi thanks! I can give it a shot

**Comment by yspotts** [comment]
@hbagdi https://github.com/Kong/charts/pull/10
