### ISSUE TITLE
Validate that env values are strings (and not bools/numbers)

### ISSUE THREAD

**Issue by randmonkey** [Kong/charts#701]
Values with unexpected types render templates may cause unexpected behavior in developing.
For example, users may set `env.proxy_access_log` to `"off"` turn off access logs, but if the value is configured to `off` (no quotes), it will be rendered to `"false"` in the final manifests. This will cause Kong to print logs to `/kong-prefix/false`, which is unexpected.
We could add validations to guarantee that only strings are used in the value. 

## Acceptance criteria
- [ ] `env` and `ingress_controller.env` disallow values of types other than `string`

**Comment by mflendrich** [comment]
It seems that the helm templating language has primitives that make this possible:

> Also see the typeOf and kindOf functions.

https://helm.sh/docs/chart_template_guide/data_types/
