### ISSUE TITLE
Unable to see client ip when using kong 

### ISSUE THREAD

**Issue by pree04** [Kong/charts#709]
Hi I have kong deployed in kubernates cluster using helm . I want to block certain ips in kong ip restriction plugin . To do so First I want to see the request with client ip . But every time I see 10.244.0.0 in pod logs .
I have set env variables in values.yml 
env:
  trusted_ips: 0.0.0.0/0,::/0
  real_ip_header: X-Forwarded-For
  real_ip_recursive: "on"

and kong-proxy 
proxy:
  type: LoadBalancer
  externalTrafficPolicy: Local

but still I am unable to see the client ip .

**Comment by rainest** [comment]
Proxy configuration and behavior should go to https://github.com/Kong/kong/discussions. This repo is only for issues related to the chart itself, not Kong in general.
