### ISSUE TITLE
Single controller deployments support in kong helm chart

### ISSUE THREAD

**Issue by pmalek** [Kong/charts#710]
When https://github.com/Kong/kubernetes-ingress-controller/issues/702 gets implemented and released, it should get full support in this helm chart.

This issue tracks the effort of adding support of said feature.

### Proposed Solution

Similarly to https://github.com/Kong/kubernetes-ingress-controller/issues/3423

- Support https://github.com/Kong/kubernetes-ingress-controller/issues/702 as an opt-in mechanism
  - Users will be able to change a setting in helm chart to enable non-sidecar model of deployment for KIC with Gateway(s)
- After sufficient soak time (several minor versions?) change the above mentioned setting to an opt-out: default value will change
  - This will be a **breaking change** hence this has to be done as a major release

## Acceptance criteria

- [ ] As a user I can deploy KIC with multiple Kong Gateways using kong's helm chart using an opt-in setting in the helm chart
- [ ] As a user I can deploy KIC with multiple Kong Gateways using kong's helm chart by default

**Comment by rainest** [comment]
Should this require any new functionality? We already support controller-only releases (disable the proxy container by toggling https://github.com/Kong/charts/blob/4f65be9ec7a304766683aba056a5649c48583545/charts/kong/values.yaml#L21 off), and you can set the controller environment to use whatever admin API URL value(s) you like manually (and I don't think there's a way to do it automatically).

We don't support a single-release option (you can't configure the chart such that it creates separate Deployments for the controller and proxy in a single release), which isn't perfectly convenient, but it's not absolutely necessary, and in line with our requiring multiple releases for most types of more complex topology (e.g. hybrid mode). I think multiple releases should be fine, especially for the initial release of single-controller.

If so, this should only require docs to indicate how you set up those multiple releases (one proxy-only, one controller-only, the latter manually set to use the former's admin API URL(s)).

**Comment by pmalek** [comment]
Maybe the name isn't especially fortunate: single controller deployments doesn't imply multiple proxy.

> and you can set the controller environment to use whatever admin API URL value(s) you like manually (and I don't think there's a way to do it automatically

That's precisely the point in my view.

The point behind the underlying feature (implemented in KIC) is to allow:

- https://github.com/Kong/kubernetes-ingress-controller/pull/3268 specifying multiple kong Admin API urls via `--kong-admin-url` . This will allow you to run multiple gateways under 1 KIC but statically: whenever a set of those URLs change, you'd have to redeploy KIC with a new set of flags/envs
- https://github.com/Kong/kubernetes-ingress-controller/issues/3400 will allow specifying a (headless) service name behind which the configured proxies are located, which will dynamically do the service discovery by adding and removing the URLs as Pods come and go.

**Comment by rainest** [comment]
> Maybe the name isn't especially fortunate: single controller deployments doesn't imply multiple proxy.

It kinda does: while a single-controller, single-proxy deployment is supported by SCD, it's not particularly interesting, as that was something you could do already without SCD. SCD is interesting when there _are_ multiple proxies. Possible point of confusion is that I'm using "proxy" the way you use "gateway", I think: "there are multiple Kong proxy instances" and "there are multiple Kong gateway instances" are basically the same thing to me.

https://github.com/Kong/kubernetes-ingress-controller/issues/3400 would mean you're no longer specifying an admin API URL, but rather a Service (or rather any replica that's currently providing an Endpoint for it).

**Comment by pmalek** [comment]
Oh my. It seems I've not used the correct wording (again?).

> Maybe the name isn't especially fortunate: single controller deployments doesn't imply multiple proxy.

I meant the name. The feature as I understand it, is all about the usage of multiple gateways with single KIC.

---

> Possible point of confusion is that I'm using "proxy" the way you use "gateway", I think: "there are multiple Kong proxy instances" and "there are multiple Kong gateway instances" are basically the same thing to me.

They are the same thing to me as well 👍 

---

> https://github.com/Kong/kubernetes-ingress-controller/issues/3400 would mean you're no longer specifying an admin API URL, but rather a Service (or rather any replica that's currently providing an Endpoint for it).

Yes and the idea would be to not need to recreate KIC's Pod and/or Deployment for that matter, with different set of flags/configs. This way you don't need to do any sort of trickery in the chart and use 1 helm release for Gateway(s), get their addresses and use those in another helm release for KIC where you use those addresses.
