### ISSUE TITLE
Version ^2.15.0 breaks mounting of cluster certificate secrets

### ISSUE THREAD

**Issue by thilohaas** [Kong/charts#717]
The change in https://github.com/Kong/charts/pull/695 seems to be breaking for a hybrid setup:
```
Error: cluster_cert: failed loading certificate from /etc/secrets/kong-cluster-cert/tls.crt
```
The cluster secrets are not mounted in the `kong-init-migrations` pod and therefore the deployment fails.

We used the template provided by https://github.com/Kong/charts/blob/main/charts/kong/example-values/minimal-kong-enterprise-hybrid-control.yaml together with the corresponding data plane.

After downgrading to helm charts v2.14.0 everything works fine again.

**Comment by tysoekong** [comment]
Ref for all: use Helm version switch to pin the chart, if you are constantly doing `repo update` ->

```sh
helm upgrade -i my-kong kong/kong -n namespace --version 2.14.0
```
