### ISSUE TITLE
How to create both a public and private LoadBalancer?

### ISSUE THREAD

**Issue by nesl247** [Kong/charts#76]
We have services that are private and some that are public. How would we go about creating 2 `LoadBalancer`s with the helm chart to support that? Istio's helm chart supports this, but we are switching away to a `Linkerd` + `Kong` setup.

**Comment by hbagdi** [comment]
This is currently not possible within the chart.
You can easily create an umbrella chart which include's Kong chart as a sub-chart and add the other LB in the parent chart.

**Comment by nesl247** [comment]
I had wanted to see if there was a recommended way, but in the end, I ended up with 2 full installations. I had to look through the templates though because the `ingressClass` does not show as configurable in `values.yaml` even though it is. Nor was it mentioned in the `README.md`.

**Comment by hbagdi** [comment]
It is documented at the following locations:
https://github.com/Kong/charts/blob/master/charts/kong/README.md

https://github.com/Kong/charts/blob/master/charts/kong/values.yaml#L203

**Comment by nesl247** [comment]
I think I may have been searching for `ingress.class` to get the value. My vault.
