### ISSUE TITLE
kong nlb ingress supports https or not?? please help me on this. Facing issue from yesterday

### ISSUE THREAD

**Issue by Naresh240** [Kong/charts#785]

**Comment by RenataLAzevedo** [comment]
I don't know your specific scenario, but from my experience, yes, kong nlb supports https.

**Comment by rainest** [comment]
Our proxy does support HTTPS, and NLBs are our recommended load balancer type on AWS.

Closing this as there's limited info in the report and nothing that indicates a bug. Please find us on our [support channels](https://github.com/kong/kubernetes-ingress-controller#seeking-help) are available if you have general usage questions or need help diagnosing an issue.
