### ISSUE TITLE
Allow annotations to be set on admission webhook

### ISSUE THREAD

**Issue by jeroen-s** [Kong/charts#799]
To enable https://cert-manager.io/docs/concepts/ca-injector/

**Comment by kylekluever** [comment]
Isn't this already available? 
https://github.com/Kong/charts/blob/main/charts/kong/templates/admission-webhook.yaml#L38-L41

**Comment by jeroen-s** [comment]
Great.I was using version 2.13.1 of the chart which doesn't have it but it was added since. Should've look better!
