### ISSUE TITLE
Kong pod is getting crashloopback after abrupt shutdown 

### ISSUE THREAD

**Issue by soorajsomans** [Kong/charts#836]
Im using kong gateway in a single node kubernetes cluster. The kong pod is getting CrashLoopBackOff after a abrupt shutdown, 
eg. container killed forcefully or system shutdown due to power failure or system crash
On the next system start kubernets brings the pod but the state is always CrashLoopBackoff. The below error where shown in the proxy container logs

nginx: [emerg] bind() to unix:/kong_prefix/worker_events.sock failed (98: Address in use)
[notice] 1#0: try again to bind() after 500ms

In the kong container /kong_prefix/worker_events.sock file is mounted using empty dir and this not get cleaned up during abrupt shutdown. 

I have solved this issue by cleaning this file in clear-stale-pid init container. I have updated the command in like below

Please find the below pull request for the solution i have tried
https://github.com/Kong/charts/pull/837

Please suggest me if there is a better approach to handle this problem. Can you please address this issue in your upcoming releases?

**Comment by rainest** [comment]
Which Kong images are you using? This looks like something we addressed in the image earlier: https://github.com/Kong/docker-kong/pull/620

You would need Kong image 3.2.2+ for that fix.

**Comment by soorajsomans** [comment]
I'm using kong 3.0 image. I can't update the image right now,  Is there any issue with the above mentioned fix?. I have tested multiple times and its working. Please suggest if any changes required or any possible errors with this fix. Thanks in advance.

**Comment by rainest** [comment]
We'd prefer to have only the one fix rather than multiple overlapping ones. The chart-level workaround should go away once versions older than 3.2 are EOL (after the end of 2023).

https://github.com/Kong/charts/pull/837#pullrequestreview-1533334571 for changes.

**Comment by soorajsomans** [comment]
Thank you for your support. I'm planning for the image upgrade.
