### ISSUE TITLE
Improve homepage of Helm Chart

### ISSUE THREAD

**Issue by programmer04** [Kong/charts#845]
Currently, page https://charts.konghq.com contains the below
<img width="1054" alt="image" src="https://github.com/Kong/charts/assets/9593424/f0dae03f-26e1-48a7-9f06-78f9a999b811">

It doesn't include information about [kong/ingress](https://github.com/Kong/charts/blob/main/charts/ingress/README.md). It should contain clear guidelines for when to use which one.

Other minor issues
- comment `# Helm 3` seems to be redundant since [previous versions are deprecated](https://helm.sh/blog/helm-v2-deprecation-timeline/) for a long time
- including `$` with commands make them harder to copy, because you have to omit `$`

**Comment by mheap** [comment]
This was resolved by https://github.com/Kong/charts/pull/874
