### ISSUE TITLE
Chart Image Not Valid Semantic Version

### ISSUE THREAD

**Issue by dsl3zm** [Kong/charts#856]
We are using the most recent version of the kong helm chart (2.26) and this morning we are unable to update or install kong on our clusters. 

When we attempt to deploy, we are getting the following error (we have not changed anything with our values file)
![image](https://github.com/Kong/charts/assets/54951293/2db0bd7b-eca2-4406-bbdf-d94fd5998377)

"error calling semverCompare: Invalid Semantic Version"

**Comment by wombat** [comment]
We are having the same issue - we have specified the image tag to be `3.4.0.0` (which is not a valid SemVer) and ran into it.
After using the `3.4` tag, it worked again but once this gets retagged we won´t be using the latest bugfix release so I will consider this a temporary workaround.
