### ISSUE TITLE
Clean up the logic related to installCRDs.

### ISSUE THREAD

**Issue by tao12345666333** [Kong/charts#948]
We have already removed the `installCRDs` configuration item from the `values.yaml` file. 
https://github.com/Kong/charts/commit/bf98a5cbae44af1f30c72f0d0d4f1910a38a0d8c

As a result, the logic related to  `installCRDs` will not work as expected.

https://github.com/Kong/charts/blob/5c74afe783d8b3905d7117b9836ddd1eb09b991e/charts/kong/templates/custom-resource-definitions.yaml#L1-L34

I will send a PR to clean up related logic

**Comment by rainest** [comment]
Closed per https://github.com/Kong/charts/pull/949#issuecomment-1816933641. If we want to remove this we need some path we've tested to confirm it does not delete CRDs coming from ancient installs.
